/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12workgraphproperties.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12WORKGRAPHPROPERTIES_H
#define NPT_PROTOCOL_HOST_ID3D12WORKGRAPHPROPERTIES_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12WorkGraphProperties::GetNumWorkGraphs
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs {
    void *_self;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumWorkGraphs_args_temp(struct npt_cs_decoder *dec,
                                                                struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNumWorkGraphs_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply(struct npt_cs_encoder *enc,
                                                            const struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumWorkGraphs),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNumWorkGraphs(struct npt_dispatch_context *ctx,
                                                        uint32_t cmd_flags,
                                                        uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNumWorkGraphs args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNumWorkGraphs_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumWorkGraphs on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNumWorkGraphs_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumWorkGraphs: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNumWorkGraphs _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNumWorkGraphs, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNumWorkGraphs);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNumWorkGraphs) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNumWorkGraphs(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNumWorkGraphs_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetProgramName
 */

struct npt_command_ID3D12WorkGraphProperties_GetProgramName {
    void *_self;
    UINT WorkGraphIndex;
    WCHAR ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetProgramName_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_ID3D12WorkGraphProperties_GetProgramName *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetProgramName_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetProgramName *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetProgramName_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_ID3D12WorkGraphProperties_GetProgramName *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetProgramName),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetProgramName(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetProgramName args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetProgramName_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetProgramName on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetProgramName_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetProgramName: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetProgramName _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetProgramName, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetProgramName);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetProgramName) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetProgramName(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetProgramName_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetWorkGraphIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex {
    void *_self;
    const WCHAR * pProgramName;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetWorkGraphIndex_args_temp(struct npt_cs_decoder *dec,
                                                                 struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pProgramName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pProgramName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pProgramName, _wstr_size);
        } else {
            args->pProgramName = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetWorkGraphIndex_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(struct npt_cs_encoder *enc,
                                                             const struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphIndex),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetWorkGraphIndex(struct npt_dispatch_context *ctx,
                                                         uint32_t cmd_flags,
                                                         uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphIndex args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetWorkGraphIndex_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetWorkGraphIndex on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetWorkGraphIndex_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetWorkGraphIndex: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetWorkGraphIndex _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetWorkGraphIndex, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetWorkGraphIndex);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetWorkGraphIndex) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetWorkGraphIndex(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pProgramName);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetWorkGraphIndex_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetNumNodes
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumNodes {
    void *_self;
    UINT WorkGraphIndex;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumNodes_args_temp(struct npt_cs_decoder *dec,
                                                           struct npt_command_ID3D12WorkGraphProperties_GetNumNodes *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNumNodes_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNumNodes *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumNodes_reply(struct npt_cs_encoder *enc,
                                                       const struct npt_command_ID3D12WorkGraphProperties_GetNumNodes *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumNodes),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNumNodes(struct npt_dispatch_context *ctx,
                                                   uint32_t cmd_flags,
                                                   uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNumNodes args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNumNodes_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumNodes on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNumNodes_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumNodes: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNumNodes _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNumNodes, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNumNodes);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNumNodes) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNumNodes(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNumNodes_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetNodeID
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeID {
    void *_self;
    UINT WorkGraphIndex;
    UINT NodeIndex;
    D3D12_NODE_ID ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeID_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3D12WorkGraphProperties_GetNodeID *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_UINT(dec, &args->NodeIndex);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNodeID_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNodeID *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeID_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3D12WorkGraphProperties_GetNodeID *args)
{
    /* ID3D12WorkGraphProperties::GetNodeID: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNodeID(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNodeID args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNodeID_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeID on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNodeID_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeID: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNodeID _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNodeID, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNodeID);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeID) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeID(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret, args.WorkGraphIndex, args.NodeIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNodeID_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetNodeIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_NODE_ID NodeID;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeIndex_args_temp(struct npt_cs_decoder *dec,
                                                            struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_D3D12_NODE_ID(dec, &args->NodeID);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNodeIndex_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeIndex_reply(struct npt_cs_encoder *enc,
                                                        const struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNodeIndex),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNodeIndex(struct npt_dispatch_context *ctx,
                                                    uint32_t cmd_flags,
                                                    uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNodeIndex args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNodeIndex_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeIndex on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNodeIndex_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeIndex: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNodeIndex _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNodeIndex, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNodeIndex);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeIndex) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeIndex(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex, args.NodeID);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNodeIndex_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetNodeLocalRootArgumentsTableIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex {
    void *_self;
    UINT WorkGraphIndex;
    UINT NodeIndex;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_args_temp(struct npt_cs_decoder *dec,
                                                                                   struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_UINT(dec, &args->NodeIndex);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(struct npt_cs_encoder *enc,
                                                                               const struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex(struct npt_dispatch_context *ctx,
                                                                           uint32_t cmd_flags,
                                                                           uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeLocalRootArgumentsTableIndex) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNodeLocalRootArgumentsTableIndex(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex, args.NodeIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNodeLocalRootArgumentsTableIndex_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetNumEntrypoints
 */

struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints {
    void *_self;
    UINT WorkGraphIndex;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetNumEntrypoints_args_temp(struct npt_cs_decoder *dec,
                                                                 struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetNumEntrypoints_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(struct npt_cs_encoder *enc,
                                                             const struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetNumEntrypoints),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetNumEntrypoints(struct npt_dispatch_context *ctx,
                                                         uint32_t cmd_flags,
                                                         uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetNumEntrypoints args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetNumEntrypoints_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumEntrypoints on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetNumEntrypoints_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetNumEntrypoints: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetNumEntrypoints _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetNumEntrypoints, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetNumEntrypoints);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetNumEntrypoints) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetNumEntrypoints(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetNumEntrypoints_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointID
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID {
    void *_self;
    UINT WorkGraphIndex;
    UINT EntrypointIndex;
    D3D12_NODE_ID ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointID_args_temp(struct npt_cs_decoder *dec,
                                                               struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_UINT(dec, &args->EntrypointIndex);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetEntrypointID_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointID_reply(struct npt_cs_encoder *enc,
                                                           const struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID *args)
{
    /* ID3D12WorkGraphProperties::GetEntrypointID: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetEntrypointID(struct npt_dispatch_context *ctx,
                                                       uint32_t cmd_flags,
                                                       uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetEntrypointID args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetEntrypointID_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointID on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetEntrypointID_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointID: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetEntrypointID _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetEntrypointID, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetEntrypointID);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointID) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointID(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret, args.WorkGraphIndex, args.EntrypointIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetEntrypointID_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointIndex
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_NODE_ID NodeID;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointIndex_args_temp(struct npt_cs_decoder *dec,
                                                                  struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_D3D12_NODE_ID(dec, &args->NodeID);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetEntrypointIndex_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(struct npt_cs_encoder *enc,
                                                              const struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointIndex),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetEntrypointIndex(struct npt_dispatch_context *ctx,
                                                          uint32_t cmd_flags,
                                                          uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetEntrypointIndex args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetEntrypointIndex_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointIndex on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetEntrypointIndex_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointIndex: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetEntrypointIndex _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetEntrypointIndex, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetEntrypointIndex);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointIndex) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointIndex(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex, args.NodeID);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetEntrypointIndex_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetEntrypointRecordSizeInBytes
 */

struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes {
    void *_self;
    UINT WorkGraphIndex;
    UINT EntrypointIndex;
    UINT ret;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_args_temp(struct npt_cs_decoder *dec,
                                                                              struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);
    npt_decode_UINT(dec, &args->EntrypointIndex);
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(struct npt_cs_encoder *enc,
                                                                          const struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes(struct npt_dispatch_context *ctx,
                                                                      uint32_t cmd_flags,
                                                                      uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointRecordSizeInBytes) {
        args.ret = ctx->id3d12workgraphproperties_dispatch_overrides->GetEntrypointRecordSizeInBytes(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.WorkGraphIndex, args.EntrypointIndex);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetEntrypointRecordSizeInBytes_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12WorkGraphProperties::GetWorkGraphMemoryRequirements
 */

struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements {
    void *_self;
    UINT WorkGraphIndex;
    D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS * pWorkGraphMemoryRequirements;
};

static inline void
npt_decode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_args_temp(struct npt_cs_decoder *dec,
                                                                              struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->WorkGraphIndex);

    /* Allocate temp storage for output-only parameters */

    args->pWorkGraphMemoryRequirements = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS));
    if (!args->pWorkGraphMemoryRequirements) return;
    memset(args->pWorkGraphMemoryRequirements, 0, sizeof(D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS));
}

static inline void
npt_replace_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements *args)
{
}

static inline void
npt_encode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(struct npt_cs_encoder *enc,
                                                                          const struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12WorkGraphProperties,
                                 NPT_METHOD_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pWorkGraphMemoryRequirements))
        npt_encode_D3D12_WORK_GRAPH_MEMORY_REQUIREMENTS(enc, args->pWorkGraphMemoryRequirements);
}

static inline void
npt_dispatch_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements(struct npt_dispatch_context *ctx,
                                                                      uint32_t cmd_flags,
                                                                      uint64_t object_id)
{
    struct npt_command_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12WORKGRAPHPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements);

    if (ctx->id3d12workgraphproperties_dispatch_overrides && ctx->id3d12workgraphproperties_dispatch_overrides->GetWorkGraphMemoryRequirements) {
        ctx->id3d12workgraphproperties_dispatch_overrides->GetWorkGraphMemoryRequirements(ctx, &args, _original);
    } else {
        _original(args._self, args.WorkGraphIndex, args.pWorkGraphMemoryRequirements);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12WorkGraphProperties_GetWorkGraphMemoryRequirements_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12WORKGRAPHPROPERTIES_H */
