/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for idxgioutputduplication.
 */

#ifndef NPT_PROTOCOL_HOST_IDXGIOUTPUTDUPLICATION_H
#define NPT_PROTOCOL_HOST_IDXGIOUTPUTDUPLICATION_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * IDXGIOutputDuplication::GetDesc
 */

struct npt_command_IDXGIOutputDuplication_GetDesc {
    void *_self;
    DXGI_OUTDUPL_DESC * pDesc;
};

static inline void
npt_decode_IDXGIOutputDuplication_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                                    struct npt_command_IDXGIOutputDuplication_GetDesc *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_OUTDUPL_DESC));
    if (!args->pDesc) return;
    memset(args->pDesc, 0, sizeof(DXGI_OUTDUPL_DESC));
}

static inline void
npt_replace_IDXGIOutputDuplication_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_GetDesc *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_GetDesc_reply(struct npt_cs_encoder *enc,
                                                const struct npt_command_IDXGIOutputDuplication_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pDesc))
        npt_encode_DXGI_OUTDUPL_DESC(enc, args->pDesc);
}

static inline void
npt_dispatch_IDXGIOutputDuplication_GetDesc(struct npt_dispatch_context *ctx,
                                            uint32_t cmd_flags,
                                            uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetDesc on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_GetDesc_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetDesc: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_GetDesc);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->GetDesc) {
        ctx->idxgioutputduplication_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        _original(args._self, args.pDesc);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::AcquireNextFrame
 */

struct npt_command_IDXGIOutputDuplication_AcquireNextFrame {
    void *_self;
    UINT TimeoutInMilliseconds;
    DXGI_OUTDUPL_FRAME_INFO * pFrameInfo;
    IDXGIResource ** ppDesktopResource;
    /* Shadow: the guest-allocated id for ppDesktopResource arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppDesktopResource -> *ppDesktopResource} in the
     * context object table. */
    uint64_t _guest_id_ppDesktopResource;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_AcquireNextFrame_args_temp(struct npt_cs_decoder *dec,
                                                             struct npt_command_IDXGIOutputDuplication_AcquireNextFrame *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->TimeoutInMilliseconds);

    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppDesktopResource = _gid;
        args->ppDesktopResource = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppDesktopResource) return;
        *args->ppDesktopResource = NULL;
    }
    /* Allocate temp storage for output-only parameters */

    args->pFrameInfo = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_OUTDUPL_FRAME_INFO));
    if (!args->pFrameInfo) return;
    memset(args->pFrameInfo, 0, sizeof(DXGI_OUTDUPL_FRAME_INFO));

}

static inline void
npt_replace_IDXGIOutputDuplication_AcquireNextFrame_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_AcquireNextFrame *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_AcquireNextFrame_reply(struct npt_cs_encoder *enc,
                                                         const struct npt_command_IDXGIOutputDuplication_AcquireNextFrame *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_AcquireNextFrame),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pFrameInfo))
        npt_encode_DXGI_OUTDUPL_FRAME_INFO(enc, args->pFrameInfo);
/* skip args->ppDesktopResource (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_IDXGIOutputDuplication_AcquireNextFrame(struct npt_dispatch_context *ctx,
                                                     uint32_t cmd_flags,
                                                     uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_AcquireNextFrame args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_AcquireNextFrame_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_AcquireNextFrame on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_AcquireNextFrame_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_AcquireNextFrame: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_AcquireNextFrame _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_AcquireNextFrame, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_AcquireNextFrame);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->AcquireNextFrame) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->AcquireNextFrame(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.TimeoutInMilliseconds, args.pFrameInfo, args.ppDesktopResource);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppDesktopResource && *args.ppDesktopResource)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppDesktopResource, *args.ppDesktopResource, NPT_OBJECT_TYPE_IDXGIRESOURCE);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_AcquireNextFrame_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::GetFrameDirtyRects
 */

struct npt_command_IDXGIOutputDuplication_GetFrameDirtyRects {
    void *_self;
    UINT DirtyRectsBufferSize;
    void * pDirtyRectsBuffer;
    UINT * pDirtyRectsBufferSizeRequired;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_GetFrameDirtyRects_args_temp(struct npt_cs_decoder *dec,
                                                               struct npt_command_IDXGIOutputDuplication_GetFrameDirtyRects *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->DirtyRectsBufferSize);


    /* Allocate temp storage for output-only parameters */

    if (args->DirtyRectsBufferSize) {
        args->pDirtyRectsBuffer = npt_cs_decoder_alloc_temp(dec, args->DirtyRectsBufferSize);
        if (!args->pDirtyRectsBuffer) return;
        memset(args->pDirtyRectsBuffer, 0, args->DirtyRectsBufferSize);
    } else {
        args->pDirtyRectsBuffer = NULL;
    }
    args->pDirtyRectsBufferSizeRequired = npt_cs_decoder_alloc_temp(dec, sizeof(UINT));
    if (!args->pDirtyRectsBufferSizeRequired) return;
    memset(args->pDirtyRectsBufferSizeRequired, 0, sizeof(UINT));
}

static inline void
npt_replace_IDXGIOutputDuplication_GetFrameDirtyRects_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_GetFrameDirtyRects *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_GetFrameDirtyRects_reply(struct npt_cs_encoder *enc,
                                                           const struct npt_command_IDXGIOutputDuplication_GetFrameDirtyRects *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_GetFrameDirtyRects),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    /* pDirtyRectsBuffer: array sized by output count 'pDirtyRectsBufferSizeRequired'.  On
     * failure the host may have written the required count but left the
     * array contents unpopulated, so only encode elements on success. */
    if ((HRESULT)args->ret >= 0) {
        if (args->pDirtyRectsBuffer) {
        npt_encode_array_count(enc, *args->pDirtyRectsBufferSizeRequired);
        npt_encode_blob_array(enc, args->pDirtyRectsBuffer, *args->pDirtyRectsBufferSizeRequired);
    } else {
        npt_encode_array_count(enc, 0);
    }
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (npt_encode_simple_pointer(enc, args->pDirtyRectsBufferSizeRequired))
        npt_encode_UINT(enc, args->pDirtyRectsBufferSizeRequired);
}

static inline void
npt_dispatch_IDXGIOutputDuplication_GetFrameDirtyRects(struct npt_dispatch_context *ctx,
                                                       uint32_t cmd_flags,
                                                       uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_GetFrameDirtyRects args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_GetFrameDirtyRects_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFrameDirtyRects on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_GetFrameDirtyRects_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFrameDirtyRects: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_GetFrameDirtyRects _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_GetFrameDirtyRects, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_GetFrameDirtyRects);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->GetFrameDirtyRects) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->GetFrameDirtyRects(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.DirtyRectsBufferSize, args.pDirtyRectsBuffer, args.pDirtyRectsBufferSizeRequired);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_GetFrameDirtyRects_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::GetFrameMoveRects
 */

struct npt_command_IDXGIOutputDuplication_GetFrameMoveRects {
    void *_self;
    UINT MoveRectsBufferSize;
    void * pMoveRectBuffer;
    UINT * pMoveRectsBufferSizeRequired;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_GetFrameMoveRects_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_IDXGIOutputDuplication_GetFrameMoveRects *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->MoveRectsBufferSize);


    /* Allocate temp storage for output-only parameters */

    if (args->MoveRectsBufferSize) {
        args->pMoveRectBuffer = npt_cs_decoder_alloc_temp(dec, args->MoveRectsBufferSize);
        if (!args->pMoveRectBuffer) return;
        memset(args->pMoveRectBuffer, 0, args->MoveRectsBufferSize);
    } else {
        args->pMoveRectBuffer = NULL;
    }
    args->pMoveRectsBufferSizeRequired = npt_cs_decoder_alloc_temp(dec, sizeof(UINT));
    if (!args->pMoveRectsBufferSizeRequired) return;
    memset(args->pMoveRectsBufferSizeRequired, 0, sizeof(UINT));
}

static inline void
npt_replace_IDXGIOutputDuplication_GetFrameMoveRects_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_GetFrameMoveRects *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_GetFrameMoveRects_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_IDXGIOutputDuplication_GetFrameMoveRects *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_GetFrameMoveRects),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    /* pMoveRectBuffer: array sized by output count 'pMoveRectsBufferSizeRequired'.  On
     * failure the host may have written the required count but left the
     * array contents unpopulated, so only encode elements on success. */
    if ((HRESULT)args->ret >= 0) {
        if (args->pMoveRectBuffer) {
        npt_encode_array_count(enc, *args->pMoveRectsBufferSizeRequired);
        npt_encode_blob_array(enc, args->pMoveRectBuffer, *args->pMoveRectsBufferSizeRequired);
    } else {
        npt_encode_array_count(enc, 0);
    }
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (npt_encode_simple_pointer(enc, args->pMoveRectsBufferSizeRequired))
        npt_encode_UINT(enc, args->pMoveRectsBufferSizeRequired);
}

static inline void
npt_dispatch_IDXGIOutputDuplication_GetFrameMoveRects(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_GetFrameMoveRects args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_GetFrameMoveRects_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFrameMoveRects on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_GetFrameMoveRects_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFrameMoveRects: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_GetFrameMoveRects _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_GetFrameMoveRects, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_GetFrameMoveRects);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->GetFrameMoveRects) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->GetFrameMoveRects(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.MoveRectsBufferSize, args.pMoveRectBuffer, args.pMoveRectsBufferSizeRequired);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_GetFrameMoveRects_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::GetFramePointerShape
 */

struct npt_command_IDXGIOutputDuplication_GetFramePointerShape {
    void *_self;
    UINT PointerShapeBufferSize;
    void * pPointerShapeBuffer;
    UINT * pPointerShapeBufferSizeRequired;
    DXGI_OUTDUPL_POINTER_SHAPE_INFO * pPointerShapeInfo;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_GetFramePointerShape_args_temp(struct npt_cs_decoder *dec,
                                                                 struct npt_command_IDXGIOutputDuplication_GetFramePointerShape *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->PointerShapeBufferSize);



    /* Allocate temp storage for output-only parameters */

    if (args->PointerShapeBufferSize) {
        args->pPointerShapeBuffer = npt_cs_decoder_alloc_temp(dec, args->PointerShapeBufferSize);
        if (!args->pPointerShapeBuffer) return;
        memset(args->pPointerShapeBuffer, 0, args->PointerShapeBufferSize);
    } else {
        args->pPointerShapeBuffer = NULL;
    }
    args->pPointerShapeBufferSizeRequired = npt_cs_decoder_alloc_temp(dec, sizeof(UINT));
    if (!args->pPointerShapeBufferSizeRequired) return;
    memset(args->pPointerShapeBufferSizeRequired, 0, sizeof(UINT));
    args->pPointerShapeInfo = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_OUTDUPL_POINTER_SHAPE_INFO));
    if (!args->pPointerShapeInfo) return;
    memset(args->pPointerShapeInfo, 0, sizeof(DXGI_OUTDUPL_POINTER_SHAPE_INFO));
}

static inline void
npt_replace_IDXGIOutputDuplication_GetFramePointerShape_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_GetFramePointerShape *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_GetFramePointerShape_reply(struct npt_cs_encoder *enc,
                                                             const struct npt_command_IDXGIOutputDuplication_GetFramePointerShape *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_GetFramePointerShape),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    /* pPointerShapeBuffer: array sized by output count 'pPointerShapeBufferSizeRequired'.  On
     * failure the host may have written the required count but left the
     * array contents unpopulated, so only encode elements on success. */
    if ((HRESULT)args->ret >= 0) {
        if (args->pPointerShapeBuffer) {
        npt_encode_array_count(enc, *args->pPointerShapeBufferSizeRequired);
        npt_encode_blob_array(enc, args->pPointerShapeBuffer, *args->pPointerShapeBufferSizeRequired);
    } else {
        npt_encode_array_count(enc, 0);
    }
    } else {
        npt_encode_array_count(enc, 0);
    }
    if (npt_encode_simple_pointer(enc, args->pPointerShapeBufferSizeRequired))
        npt_encode_UINT(enc, args->pPointerShapeBufferSizeRequired);
    if (npt_encode_simple_pointer(enc, args->pPointerShapeInfo))
        npt_encode_DXGI_OUTDUPL_POINTER_SHAPE_INFO(enc, args->pPointerShapeInfo);
}

static inline void
npt_dispatch_IDXGIOutputDuplication_GetFramePointerShape(struct npt_dispatch_context *ctx,
                                                         uint32_t cmd_flags,
                                                         uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_GetFramePointerShape args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_GetFramePointerShape_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFramePointerShape on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_GetFramePointerShape_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_GetFramePointerShape: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_GetFramePointerShape _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_GetFramePointerShape, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_GetFramePointerShape);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->GetFramePointerShape) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->GetFramePointerShape(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.PointerShapeBufferSize, args.pPointerShapeBuffer, args.pPointerShapeBufferSizeRequired, args.pPointerShapeInfo);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_GetFramePointerShape_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::MapDesktopSurface
 */

struct npt_command_IDXGIOutputDuplication_MapDesktopSurface {
    void *_self;
    DXGI_MAPPED_RECT * pLockedRect;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_MapDesktopSurface_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_IDXGIOutputDuplication_MapDesktopSurface *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pLockedRect = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_MAPPED_RECT));
    if (!args->pLockedRect) return;
    memset(args->pLockedRect, 0, sizeof(DXGI_MAPPED_RECT));
}

static inline void
npt_replace_IDXGIOutputDuplication_MapDesktopSurface_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_MapDesktopSurface *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_MapDesktopSurface_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_IDXGIOutputDuplication_MapDesktopSurface *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_MapDesktopSurface),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pLockedRect))
        npt_encode_DXGI_MAPPED_RECT(enc, args->pLockedRect);
}

static inline void
npt_dispatch_IDXGIOutputDuplication_MapDesktopSurface(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_MapDesktopSurface args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_MapDesktopSurface_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_MapDesktopSurface on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_MapDesktopSurface_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_MapDesktopSurface: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_MapDesktopSurface _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_MapDesktopSurface, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_MapDesktopSurface);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->MapDesktopSurface) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->MapDesktopSurface(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pLockedRect);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_MapDesktopSurface_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::UnMapDesktopSurface
 */

struct npt_command_IDXGIOutputDuplication_UnMapDesktopSurface {
    void *_self;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_UnMapDesktopSurface_args_temp(struct npt_cs_decoder *dec,
                                                                struct npt_command_IDXGIOutputDuplication_UnMapDesktopSurface *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_IDXGIOutputDuplication_UnMapDesktopSurface_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_UnMapDesktopSurface *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_UnMapDesktopSurface_reply(struct npt_cs_encoder *enc,
                                                            const struct npt_command_IDXGIOutputDuplication_UnMapDesktopSurface *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_UnMapDesktopSurface),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_IDXGIOutputDuplication_UnMapDesktopSurface(struct npt_dispatch_context *ctx,
                                                        uint32_t cmd_flags,
                                                        uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_UnMapDesktopSurface args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_UnMapDesktopSurface_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_UnMapDesktopSurface on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_UnMapDesktopSurface_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_UnMapDesktopSurface: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_UnMapDesktopSurface _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_UnMapDesktopSurface, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_UnMapDesktopSurface);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->UnMapDesktopSurface) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->UnMapDesktopSurface(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_UnMapDesktopSurface_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIOutputDuplication::ReleaseFrame
 */

struct npt_command_IDXGIOutputDuplication_ReleaseFrame {
    void *_self;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIOutputDuplication_ReleaseFrame_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_IDXGIOutputDuplication_ReleaseFrame *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_IDXGIOutputDuplication_ReleaseFrame_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIOutputDuplication_ReleaseFrame *args)
{
}

static inline void
npt_encode_IDXGIOutputDuplication_ReleaseFrame_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_IDXGIOutputDuplication_ReleaseFrame *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIOutputDuplication,
                                 NPT_METHOD_IDXGIOutputDuplication_ReleaseFrame),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_IDXGIOutputDuplication_ReleaseFrame(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_IDXGIOutputDuplication_ReleaseFrame args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIOutputDuplication_ReleaseFrame_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIOUTPUTDUPLICATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_ReleaseFrame on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIOutputDuplication_ReleaseFrame_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIOutputDuplication_ReleaseFrame: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIOutputDuplication_ReleaseFrame _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIOutputDuplication_ReleaseFrame, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIOutputDuplication_ReleaseFrame);

    if (ctx->idxgioutputduplication_dispatch_overrides && ctx->idxgioutputduplication_dispatch_overrides->ReleaseFrame) {
        args.ret = ctx->idxgioutputduplication_dispatch_overrides->ReleaseFrame(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIOutputDuplication_ReleaseFrame_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_IDXGIOUTPUTDUPLICATION_H */
