/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3duserdefinedannotation.
 */

#ifndef NPT_PROTOCOL_HOST_ID3DUSERDEFINEDANNOTATION_H
#define NPT_PROTOCOL_HOST_ID3DUSERDEFINEDANNOTATION_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3DUserDefinedAnnotation::BeginEvent
 */

struct npt_command_ID3DUserDefinedAnnotation_BeginEvent {
    void *_self;
    const WCHAR * Name;
    INT ret;
};

static inline void
npt_decode_ID3DUserDefinedAnnotation_BeginEvent_args_temp(struct npt_cs_decoder *dec,
                                                          struct npt_command_ID3DUserDefinedAnnotation_BeginEvent *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->Name = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->Name) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->Name, _wstr_size);
        } else {
            args->Name = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3DUserDefinedAnnotation_BeginEvent_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3DUserDefinedAnnotation_BeginEvent *args)
{
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_BeginEvent_reply(struct npt_cs_encoder *enc,
                                                      const struct npt_command_ID3DUserDefinedAnnotation_BeginEvent *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_BeginEvent),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3DUserDefinedAnnotation_BeginEvent(struct npt_dispatch_context *ctx,
                                                  uint32_t cmd_flags,
                                                  uint64_t object_id)
{
    struct npt_command_ID3DUserDefinedAnnotation_BeginEvent args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3DUserDefinedAnnotation_BeginEvent_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3DUSERDEFINEDANNOTATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_BeginEvent on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3DUserDefinedAnnotation_BeginEvent_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_BeginEvent: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3DUserDefinedAnnotation_BeginEvent _original = NPT_COM_VTBL_FUNC(
        PFN_ID3DUserDefinedAnnotation_BeginEvent, npt_com_vtable(args._self),
        NPT_VTBL_ID3DUserDefinedAnnotation_BeginEvent);

    if (ctx->id3duserdefinedannotation_dispatch_overrides && ctx->id3duserdefinedannotation_dispatch_overrides->BeginEvent) {
        args.ret = ctx->id3duserdefinedannotation_dispatch_overrides->BeginEvent(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.Name);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3DUserDefinedAnnotation_BeginEvent_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3DUserDefinedAnnotation::EndEvent
 */

struct npt_command_ID3DUserDefinedAnnotation_EndEvent {
    void *_self;
    INT ret;
};

static inline void
npt_decode_ID3DUserDefinedAnnotation_EndEvent_args_temp(struct npt_cs_decoder *dec,
                                                        struct npt_command_ID3DUserDefinedAnnotation_EndEvent *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3DUserDefinedAnnotation_EndEvent_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3DUserDefinedAnnotation_EndEvent *args)
{
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_EndEvent_reply(struct npt_cs_encoder *enc,
                                                    const struct npt_command_ID3DUserDefinedAnnotation_EndEvent *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_EndEvent),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3DUserDefinedAnnotation_EndEvent(struct npt_dispatch_context *ctx,
                                                uint32_t cmd_flags,
                                                uint64_t object_id)
{
    struct npt_command_ID3DUserDefinedAnnotation_EndEvent args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3DUserDefinedAnnotation_EndEvent_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3DUSERDEFINEDANNOTATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_EndEvent on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3DUserDefinedAnnotation_EndEvent_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_EndEvent: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3DUserDefinedAnnotation_EndEvent _original = NPT_COM_VTBL_FUNC(
        PFN_ID3DUserDefinedAnnotation_EndEvent, npt_com_vtable(args._self),
        NPT_VTBL_ID3DUserDefinedAnnotation_EndEvent);

    if (ctx->id3duserdefinedannotation_dispatch_overrides && ctx->id3duserdefinedannotation_dispatch_overrides->EndEvent) {
        args.ret = ctx->id3duserdefinedannotation_dispatch_overrides->EndEvent(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3DUserDefinedAnnotation_EndEvent_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3DUserDefinedAnnotation::SetMarker
 */

struct npt_command_ID3DUserDefinedAnnotation_SetMarker {
    void *_self;
    const WCHAR * Name;
};

static inline void
npt_decode_ID3DUserDefinedAnnotation_SetMarker_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3DUserDefinedAnnotation_SetMarker *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->Name = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->Name) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->Name, _wstr_size);
        } else {
            args->Name = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3DUserDefinedAnnotation_SetMarker_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3DUserDefinedAnnotation_SetMarker *args)
{
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_SetMarker_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3DUserDefinedAnnotation_SetMarker *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_SetMarker),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3DUserDefinedAnnotation_SetMarker(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3DUserDefinedAnnotation_SetMarker args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3DUserDefinedAnnotation_SetMarker_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3DUSERDEFINEDANNOTATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_SetMarker on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3DUserDefinedAnnotation_SetMarker_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_SetMarker: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3DUserDefinedAnnotation_SetMarker _original = NPT_COM_VTBL_FUNC(
        PFN_ID3DUserDefinedAnnotation_SetMarker, npt_com_vtable(args._self),
        NPT_VTBL_ID3DUserDefinedAnnotation_SetMarker);

    if (ctx->id3duserdefinedannotation_dispatch_overrides && ctx->id3duserdefinedannotation_dispatch_overrides->SetMarker) {
        ctx->id3duserdefinedannotation_dispatch_overrides->SetMarker(ctx, &args, _original);
    } else {
        _original(args._self, args.Name);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3DUserDefinedAnnotation_SetMarker_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3DUserDefinedAnnotation::GetStatus
 */

struct npt_command_ID3DUserDefinedAnnotation_GetStatus {
    void *_self;
    BOOL ret;
};

static inline void
npt_decode_ID3DUserDefinedAnnotation_GetStatus_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3DUserDefinedAnnotation_GetStatus *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3DUserDefinedAnnotation_GetStatus_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3DUserDefinedAnnotation_GetStatus *args)
{
}

static inline void
npt_encode_ID3DUserDefinedAnnotation_GetStatus_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3DUserDefinedAnnotation_GetStatus *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3DUserDefinedAnnotation,
                                 NPT_METHOD_ID3DUserDefinedAnnotation_GetStatus),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3DUserDefinedAnnotation_GetStatus(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3DUserDefinedAnnotation_GetStatus args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3DUserDefinedAnnotation_GetStatus_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3DUSERDEFINEDANNOTATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_GetStatus on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3DUserDefinedAnnotation_GetStatus_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3DUserDefinedAnnotation_GetStatus: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3DUserDefinedAnnotation_GetStatus _original = NPT_COM_VTBL_FUNC(
        PFN_ID3DUserDefinedAnnotation_GetStatus, npt_com_vtable(args._self),
        NPT_VTBL_ID3DUserDefinedAnnotation_GetStatus);

    if (ctx->id3duserdefinedannotation_dispatch_overrides && ctx->id3duserdefinedannotation_dispatch_overrides->GetStatus) {
        args.ret = ctx->id3duserdefinedannotation_dispatch_overrides->GetStatus(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3DUserDefinedAnnotation_GetStatus_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3DUSERDEFINEDANNOTATION_H */
