/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12pipelinelibrary.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12PIPELINELIBRARY_H
#define NPT_PROTOCOL_HOST_ID3D12PIPELINELIBRARY_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12PipelineLibrary::StorePipeline
 */

struct npt_command_ID3D12PipelineLibrary_StorePipeline {
    void *_self;
    const WCHAR * pName;
    ID3D12PipelineState * pPipeline;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary_StorePipeline_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3D12PipelineLibrary_StorePipeline *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pName, _wstr_size);
        } else {
            args->pName = NULL;
        }
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pPipeline = (ID3D12PipelineState *)npt_object_from_id(_id);
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12PipelineLibrary_StorePipeline_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary_StorePipeline *args)
{
    args->pPipeline = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pPipeline, NPT_OBJECT_TYPE_ID3D12PIPELINESTATE);
}

static inline void
npt_encode_ID3D12PipelineLibrary_StorePipeline_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3D12PipelineLibrary_StorePipeline *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary,
                                 NPT_METHOD_ID3D12PipelineLibrary_StorePipeline),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12PipelineLibrary_StorePipeline(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary_StorePipeline args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary_StorePipeline_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_StorePipeline on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary_StorePipeline_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_StorePipeline: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary_StorePipeline _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary_StorePipeline, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary_StorePipeline);

    if (ctx->id3d12pipelinelibrary_dispatch_overrides && ctx->id3d12pipelinelibrary_dispatch_overrides->StorePipeline) {
        args.ret = ctx->id3d12pipelinelibrary_dispatch_overrides->StorePipeline(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pName, args.pPipeline);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary_StorePipeline_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12PipelineLibrary::LoadGraphicsPipeline
 */

struct npt_command_ID3D12PipelineLibrary_LoadGraphicsPipeline {
    void *_self;
    const WCHAR * pName;
    const D3D12_GRAPHICS_PIPELINE_STATE_DESC * pDesc;
    const IID * riid;
    void ** ppPipelineState;
    /* Shadow: the guest-allocated id for ppPipelineState arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppPipelineState -> *ppPipelineState} in the
     * context object table. */
    uint64_t _guest_id_ppPipelineState;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary_LoadGraphicsPipeline_args_temp(struct npt_cs_decoder *dec,
                                                                struct npt_command_ID3D12PipelineLibrary_LoadGraphicsPipeline *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pName, _wstr_size);
        } else {
            args->pName = NULL;
        }
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_GRAPHICS_PIPELINE_STATE_DESC));
        if (!args->pDesc) return;
        npt_decode_D3D12_GRAPHICS_PIPELINE_STATE_DESC(dec, (D3D12_GRAPHICS_PIPELINE_STATE_DESC *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppPipelineState = _gid;
        args->ppPipelineState = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppPipelineState) return;
        *args->ppPipelineState = NULL;
    }
    /* Allocate temp storage for output-only parameters */




}

static inline void
npt_replace_ID3D12PipelineLibrary_LoadGraphicsPipeline_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary_LoadGraphicsPipeline *args)
{
    if (args->pDesc)
        npt_replace_D3D12_GRAPHICS_PIPELINE_STATE_DESC_handle(ctx, (D3D12_GRAPHICS_PIPELINE_STATE_DESC *)args->pDesc);
}

static inline void
npt_encode_ID3D12PipelineLibrary_LoadGraphicsPipeline_reply(struct npt_cs_encoder *enc,
                                                            const struct npt_command_ID3D12PipelineLibrary_LoadGraphicsPipeline *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary,
                                 NPT_METHOD_ID3D12PipelineLibrary_LoadGraphicsPipeline),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppPipelineState (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12PipelineLibrary_LoadGraphicsPipeline(struct npt_dispatch_context *ctx,
                                                        uint32_t cmd_flags,
                                                        uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary_LoadGraphicsPipeline args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary_LoadGraphicsPipeline_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_LoadGraphicsPipeline on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary_LoadGraphicsPipeline_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_LoadGraphicsPipeline: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary_LoadGraphicsPipeline _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary_LoadGraphicsPipeline, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary_LoadGraphicsPipeline);

    if (ctx->id3d12pipelinelibrary_dispatch_overrides && ctx->id3d12pipelinelibrary_dispatch_overrides->LoadGraphicsPipeline) {
        args.ret = ctx->id3d12pipelinelibrary_dispatch_overrides->LoadGraphicsPipeline(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pName, args.pDesc, args.riid, args.ppPipelineState);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppPipelineState && *args.ppPipelineState)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppPipelineState, *args.ppPipelineState,
            npt_object_type_from_iid(args.riid));
    else if (args.ppPipelineState)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary_LoadGraphicsPipeline_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12PipelineLibrary::LoadComputePipeline
 */

struct npt_command_ID3D12PipelineLibrary_LoadComputePipeline {
    void *_self;
    const WCHAR * pName;
    const D3D12_COMPUTE_PIPELINE_STATE_DESC * pDesc;
    const IID * riid;
    void ** ppPipelineState;
    /* Shadow: the guest-allocated id for ppPipelineState arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppPipelineState -> *ppPipelineState} in the
     * context object table. */
    uint64_t _guest_id_ppPipelineState;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary_LoadComputePipeline_args_temp(struct npt_cs_decoder *dec,
                                                               struct npt_command_ID3D12PipelineLibrary_LoadComputePipeline *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pName, _wstr_size);
        } else {
            args->pName = NULL;
        }
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_COMPUTE_PIPELINE_STATE_DESC));
        if (!args->pDesc) return;
        npt_decode_D3D12_COMPUTE_PIPELINE_STATE_DESC(dec, (D3D12_COMPUTE_PIPELINE_STATE_DESC *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppPipelineState = _gid;
        args->ppPipelineState = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppPipelineState) return;
        *args->ppPipelineState = NULL;
    }
    /* Allocate temp storage for output-only parameters */




}

static inline void
npt_replace_ID3D12PipelineLibrary_LoadComputePipeline_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary_LoadComputePipeline *args)
{
    if (args->pDesc)
        npt_replace_D3D12_COMPUTE_PIPELINE_STATE_DESC_handle(ctx, (D3D12_COMPUTE_PIPELINE_STATE_DESC *)args->pDesc);
}

static inline void
npt_encode_ID3D12PipelineLibrary_LoadComputePipeline_reply(struct npt_cs_encoder *enc,
                                                           const struct npt_command_ID3D12PipelineLibrary_LoadComputePipeline *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary,
                                 NPT_METHOD_ID3D12PipelineLibrary_LoadComputePipeline),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppPipelineState (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12PipelineLibrary_LoadComputePipeline(struct npt_dispatch_context *ctx,
                                                       uint32_t cmd_flags,
                                                       uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary_LoadComputePipeline args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary_LoadComputePipeline_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_LoadComputePipeline on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary_LoadComputePipeline_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_LoadComputePipeline: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary_LoadComputePipeline _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary_LoadComputePipeline, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary_LoadComputePipeline);

    if (ctx->id3d12pipelinelibrary_dispatch_overrides && ctx->id3d12pipelinelibrary_dispatch_overrides->LoadComputePipeline) {
        args.ret = ctx->id3d12pipelinelibrary_dispatch_overrides->LoadComputePipeline(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pName, args.pDesc, args.riid, args.ppPipelineState);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppPipelineState && *args.ppPipelineState)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppPipelineState, *args.ppPipelineState,
            npt_object_type_from_iid(args.riid));
    else if (args.ppPipelineState)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary_LoadComputePipeline_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12PipelineLibrary::GetSerializedSize
 */

struct npt_command_ID3D12PipelineLibrary_GetSerializedSize {
    void *_self;
    SIZE_T ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary_GetSerializedSize_args_temp(struct npt_cs_decoder *dec,
                                                             struct npt_command_ID3D12PipelineLibrary_GetSerializedSize *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12PipelineLibrary_GetSerializedSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary_GetSerializedSize *args)
{
}

static inline void
npt_encode_ID3D12PipelineLibrary_GetSerializedSize_reply(struct npt_cs_encoder *enc,
                                                         const struct npt_command_ID3D12PipelineLibrary_GetSerializedSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary,
                                 NPT_METHOD_ID3D12PipelineLibrary_GetSerializedSize),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_SIZE_T(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12PipelineLibrary_GetSerializedSize(struct npt_dispatch_context *ctx,
                                                     uint32_t cmd_flags,
                                                     uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary_GetSerializedSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary_GetSerializedSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_GetSerializedSize on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary_GetSerializedSize_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_GetSerializedSize: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary_GetSerializedSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary_GetSerializedSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary_GetSerializedSize);

    if (ctx->id3d12pipelinelibrary_dispatch_overrides && ctx->id3d12pipelinelibrary_dispatch_overrides->GetSerializedSize) {
        args.ret = ctx->id3d12pipelinelibrary_dispatch_overrides->GetSerializedSize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary_GetSerializedSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12PipelineLibrary::Serialize
 */

struct npt_command_ID3D12PipelineLibrary_Serialize {
    void *_self;
    void * pData;
    SIZE_T DataSizeInBytes;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary_Serialize_args_temp(struct npt_cs_decoder *dec,
                                                     struct npt_command_ID3D12PipelineLibrary_Serialize *args)
{
    /* Decode input parameters from the wire */

    npt_decode_SIZE_T(dec, &args->DataSizeInBytes);
    /* Allocate temp storage for output-only parameters */
    if (args->DataSizeInBytes) {
        args->pData = npt_cs_decoder_alloc_temp(dec, args->DataSizeInBytes);
        if (!args->pData) return;
        memset(args->pData, 0, args->DataSizeInBytes);
    } else {
        args->pData = NULL;
    }

}

static inline void
npt_replace_ID3D12PipelineLibrary_Serialize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary_Serialize *args)
{
}

static inline void
npt_encode_ID3D12PipelineLibrary_Serialize_reply(struct npt_cs_encoder *enc,
                                                 const struct npt_command_ID3D12PipelineLibrary_Serialize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary,
                                 NPT_METHOD_ID3D12PipelineLibrary_Serialize),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (args->pData) {
        npt_encode_array_count(enc, args->DataSizeInBytes);
        npt_encode_blob_array(enc, args->pData, args->DataSizeInBytes);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline void
npt_dispatch_ID3D12PipelineLibrary_Serialize(struct npt_dispatch_context *ctx,
                                             uint32_t cmd_flags,
                                             uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary_Serialize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary_Serialize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_Serialize on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary_Serialize_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary_Serialize: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary_Serialize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary_Serialize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary_Serialize);

    if (ctx->id3d12pipelinelibrary_dispatch_overrides && ctx->id3d12pipelinelibrary_dispatch_overrides->Serialize) {
        args.ret = ctx->id3d12pipelinelibrary_dispatch_overrides->Serialize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pData, args.DataSizeInBytes);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary_Serialize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12PipelineLibrary1::LoadPipeline
 */

struct npt_command_ID3D12PipelineLibrary1_LoadPipeline {
    void *_self;
    const WCHAR * pName;
    const D3D12_PIPELINE_STATE_STREAM_DESC * pDesc;
    const IID * riid;
    void ** ppPipelineState;
    /* Shadow: the guest-allocated id for ppPipelineState arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppPipelineState -> *ppPipelineState} in the
     * context object table. */
    uint64_t _guest_id_ppPipelineState;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12PipelineLibrary1_LoadPipeline_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3D12PipelineLibrary1_LoadPipeline *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pName, _wstr_size);
        } else {
            args->pName = NULL;
        }
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_PIPELINE_STATE_STREAM_DESC));
        if (!args->pDesc) return;
        npt_decode_D3D12_PIPELINE_STATE_STREAM_DESC(dec, (D3D12_PIPELINE_STATE_STREAM_DESC *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppPipelineState = _gid;
        args->ppPipelineState = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppPipelineState) return;
        *args->ppPipelineState = NULL;
    }
    /* Allocate temp storage for output-only parameters */




}

static inline void
npt_replace_ID3D12PipelineLibrary1_LoadPipeline_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12PipelineLibrary1_LoadPipeline *args)
{
}

static inline void
npt_encode_ID3D12PipelineLibrary1_LoadPipeline_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3D12PipelineLibrary1_LoadPipeline *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12PipelineLibrary1,
                                 NPT_METHOD_ID3D12PipelineLibrary1_LoadPipeline),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppPipelineState (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12PipelineLibrary1_LoadPipeline(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3D12PipelineLibrary1_LoadPipeline args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12PipelineLibrary1_LoadPipeline_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12PIPELINELIBRARY1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary1_LoadPipeline on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12PipelineLibrary1_LoadPipeline_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12PipelineLibrary1_LoadPipeline: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12PipelineLibrary1_LoadPipeline _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12PipelineLibrary1_LoadPipeline, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12PipelineLibrary1_LoadPipeline);

    if (ctx->id3d12pipelinelibrary1_dispatch_overrides && ctx->id3d12pipelinelibrary1_dispatch_overrides->LoadPipeline) {
        args.ret = ctx->id3d12pipelinelibrary1_dispatch_overrides->LoadPipeline(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pName, args.pDesc, args.riid, args.ppPipelineState);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppPipelineState && *args.ppPipelineState)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppPipelineState, *args.ppPipelineState,
            npt_object_type_from_iid(args.riid));
    else if (args.ppPipelineState)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppPipelineState);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12PipelineLibrary1_LoadPipeline_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12PIPELINELIBRARY_H */
