/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Low-level helpers for Neptune command stream serialization.
 * Provides blob, array-count, string, and simple-pointer primitives
 * on top of the raw encoder/decoder provided by the consuming project.
 */

#ifndef NPT_PROTOCOL_COMMON_CS_HELPERS_H
#define NPT_PROTOCOL_COMMON_CS_HELPERS_H

#include "npt_protocol_common_cs.h"

/* ------------------------------------------------------------------ */
/* Primitive scalar encode/decode                                      */
/* ------------------------------------------------------------------ */

#define NPT_DEFINE_SCALAR(type, wire_size)                                    \
static inline size_t                                                          \
npt_sizeof_##type(const type *val, int max_mode)                              \
{                                                                             \
    return (wire_size);                                                       \
}                                                                             \
                                                                              \
static inline void                                                            \
npt_encode_##type(struct npt_cs_encoder *enc, const type *val)                \
{                                                                             \
    npt_cs_encoder_write(enc, (wire_size), val, sizeof(*val));                \
}                                                                             \
                                                                              \
static inline void                                                            \
npt_decode_##type(struct npt_cs_decoder *dec, type *val)                      \
{                                                                             \
    npt_cs_decoder_read(dec, (wire_size), val, sizeof(*val));                 \
}                                                                             \
                                                                              \
static inline size_t                                                          \
npt_sizeof_##type##_array(const type *val, uint32_t count)                    \
{                                                                             \
    (void)val;                                                                \
    const size_t raw = sizeof(type) * count;                                  \
    return (sizeof(type) >= 4) ? raw : ((raw + 3) & ~(size_t)3);                         \
}                                                                             \
                                                                              \
static inline void                                                            \
npt_encode_##type##_array(struct npt_cs_encoder *enc,                         \
                          const type *val, uint32_t count)                     \
{                                                                             \
    const size_t raw = sizeof(type) * count;                                  \
    const size_t padded = (sizeof(type) >= 4) ? raw : ((raw + 3) & ~(size_t)3);          \
    npt_cs_encoder_write(enc, padded, val, raw);                              \
}                                                                             \
                                                                              \
static inline void                                                            \
npt_decode_##type##_array(struct npt_cs_decoder *dec,                         \
                          type *val, uint32_t count)                           \
{                                                                             \
    const size_t raw = sizeof(type) * count;                                  \
    const size_t padded = (sizeof(type) >= 4) ? raw : ((raw + 3) & ~(size_t)3);          \
    npt_cs_decoder_read(dec, padded, val, raw);                               \
}

NPT_DEFINE_SCALAR(uint8_t,  4)
NPT_DEFINE_SCALAR(int8_t,   4)
NPT_DEFINE_SCALAR(uint16_t, 4)
NPT_DEFINE_SCALAR(int16_t,  4)
NPT_DEFINE_SCALAR(uint32_t, 4)
NPT_DEFINE_SCALAR(int32_t,  4)
NPT_DEFINE_SCALAR(uint64_t, 8)
NPT_DEFINE_SCALAR(int64_t,  8)

/* float/double: reinterpret-cast to unsigned, then serialize */
static inline size_t npt_sizeof_float(const float *val, int max_mode) { return 4; }
static inline void npt_encode_float(struct npt_cs_encoder *enc, const float *val)
{
    npt_cs_encoder_write(enc, 4, val, sizeof(*val));
}
static inline void npt_decode_float(struct npt_cs_decoder *dec, float *val)
{
    npt_cs_decoder_read(dec, 4, val, sizeof(*val));
}
static inline size_t npt_sizeof_float_array(const float *val, uint32_t count)
{
    (void)val;
    return sizeof(float) * count;
}
static inline void npt_encode_float_array(struct npt_cs_encoder *enc,
                                          const float *val, uint32_t count)
{
    npt_cs_encoder_write(enc, sizeof(float) * count, val, sizeof(float) * count);
}
static inline void npt_decode_float_array(struct npt_cs_decoder *dec,
                                          float *val, uint32_t count)
{
    npt_cs_decoder_read(dec, sizeof(float) * count, val, sizeof(float) * count);
}

static inline size_t npt_sizeof_double(const double *val, int max_mode) { return 8; }
static inline void npt_encode_double(struct npt_cs_encoder *enc, const double *val)
{
    npt_cs_encoder_write(enc, 8, val, sizeof(*val));
}
static inline void npt_decode_double(struct npt_cs_decoder *dec, double *val)
{
    npt_cs_decoder_read(dec, 8, val, sizeof(*val));
}
static inline size_t npt_sizeof_double_array(const double *val, uint32_t count)
{
    (void)val;
    return sizeof(double) * count;
}
static inline void npt_encode_double_array(struct npt_cs_encoder *enc,
                                           const double *val, uint32_t count)
{
    npt_cs_encoder_write(enc, sizeof(double) * count, val, sizeof(double) * count);
}
static inline void npt_decode_double_array(struct npt_cs_decoder *dec,
                                           double *val, uint32_t count)
{
    npt_cs_decoder_read(dec, sizeof(double) * count, val, sizeof(double) * count);
}

#undef NPT_DEFINE_SCALAR

/* ------------------------------------------------------------------ */
/* GUID                                                                */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_GUID(const GUID *val, int max_mode)
{
    return 16;
}

static inline void npt_encode_GUID(struct npt_cs_encoder *enc, const GUID *val)
{
    npt_cs_encoder_write(enc, 16, val, sizeof(GUID));
}

static inline void npt_decode_GUID(struct npt_cs_decoder *dec, GUID *val)
{
    npt_cs_decoder_read(dec, 16, val, sizeof(GUID));
}

/* C keyword type delegates */
static inline size_t npt_sizeof_int(const int *val, int max_mode) { return npt_sizeof_int32_t((const int32_t *)val, max_mode); }
static inline void npt_encode_int(struct npt_cs_encoder *enc, const int *val) { npt_encode_int32_t(enc, (const int32_t *)val); }
static inline void npt_decode_int(struct npt_cs_decoder *dec, int *val) { npt_decode_int32_t(dec, (int32_t *)val); }

/* LONG -- needed by POINT/RECT below, before types.h is included */
static inline size_t npt_sizeof_LONG(const LONG *val, int max_mode) { return npt_sizeof_int32_t((const int32_t *)val, max_mode); }
static inline void npt_encode_LONG(struct npt_cs_encoder *enc, const LONG *val) { npt_encode_int32_t(enc, (const int32_t *)val); }
static inline void npt_decode_LONG(struct npt_cs_decoder *dec, LONG *val) { npt_decode_int32_t(dec, (int32_t *)val); }

/* ------------------------------------------------------------------ */
/* POINT { LONG x, y; }                                                */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_POINT(const POINT *val, int max_mode)
{
    return 8; /* 2 x LONG (4 bytes each) */
}

static inline void npt_encode_POINT(struct npt_cs_encoder *enc, const POINT *val)
{
    npt_encode_LONG(enc, &val->x);
    npt_encode_LONG(enc, &val->y);
}

static inline void npt_decode_POINT(struct npt_cs_decoder *dec, POINT *val)
{
    npt_decode_LONG(dec, &val->x);
    npt_decode_LONG(dec, &val->y);
}

/* ------------------------------------------------------------------ */
/* RECT { LONG left, top, right, bottom; }                             */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_RECT(const RECT *val, int max_mode)
{
    return 16; /* 4 x LONG (4 bytes each) */
}

static inline void npt_encode_RECT(struct npt_cs_encoder *enc, const RECT *val)
{
    npt_encode_LONG(enc, &val->left);
    npt_encode_LONG(enc, &val->top);
    npt_encode_LONG(enc, &val->right);
    npt_encode_LONG(enc, &val->bottom);
}

static inline void npt_decode_RECT(struct npt_cs_decoder *dec, RECT *val)
{
    npt_decode_LONG(dec, &val->left);
    npt_decode_LONG(dec, &val->top);
    npt_decode_LONG(dec, &val->right);
    npt_decode_LONG(dec, &val->bottom);
}

static inline bool npt_guid_equal(const GUID *a, const GUID *b)
{
    return memcmp(a, b, sizeof(GUID)) == 0;
}

static inline size_t npt_sizeof_RECT_array(const RECT *val, uint32_t count)
{
    (void)val;
    return 16 * count;
}

static inline void npt_encode_RECT_array(struct npt_cs_encoder *enc,
                                         const RECT *val, uint32_t count)
{
    for (uint32_t i = 0; i < count; i++)
        npt_encode_RECT(enc, &val[i]);
}

static inline void npt_decode_RECT_array(struct npt_cs_decoder *dec,
                                         RECT *val, uint32_t count)
{
    for (uint32_t i = 0; i < count; i++)
        npt_decode_RECT(dec, &val[i]);
}

/* ------------------------------------------------------------------ */
/* Opaque blob (32-bit aligned byte array)                             */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_blob_array(const void *val, size_t size)
{
    (void)val;
    return (size + 3) & ~(size_t)3;
}

static inline void npt_encode_blob_array(struct npt_cs_encoder *enc,
                                         const void *val, size_t size)
{
    npt_cs_encoder_write(enc, (size + 3) & ~(size_t)3, val, size);
}

static inline void npt_decode_blob_array(struct npt_cs_decoder *dec,
                                         void *val, size_t size)
{
    npt_cs_decoder_read(dec, (size + 3) & ~(size_t)3, val, size);
}

/* ------------------------------------------------------------------ */
/* Array element count prefix (uint64_t)                               */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_array_count(uint64_t count)
{
    (void)count;
    return sizeof(uint64_t);
}

static inline void npt_encode_array_count(struct npt_cs_encoder *enc,
                                          uint64_t count)
{
    npt_encode_uint64_t(enc, &count);
}

static inline uint64_t npt_decode_array_count(struct npt_cs_decoder *dec,
                                              uint64_t expected_count)
{
    uint64_t count;
    npt_decode_uint64_t(dec, &count);
    if (count != expected_count) {
        npt_cs_decoder_set_fatal(dec);
        count = 0;
    }
    return count;
}

static inline uint64_t npt_decode_array_count_unchecked(struct npt_cs_decoder *dec)
{
    uint64_t count;
    npt_decode_uint64_t(dec, &count);
    return count;
}

static inline uint64_t npt_peek_array_count(struct npt_cs_decoder *dec)
{
    uint64_t count;
    npt_cs_decoder_peek(dec, sizeof(count), &count, sizeof(count));
    return count;
}

/*
 * Counted pointers historically used count=0 for both NULL+0 and
 * non-NULL+0, losing pointer presence.  Keep the one-word wire format:
 *
 *   0             -> NULL
 *   UINT64_MAX    -> present pointer, logical count 0
 *   N             -> present pointer, logical count N
 *
 * UINT64_MAX is not a meaningful allocatable array length.
 */
#define NPT_COUNTED_POINTER_PRESENT_ZERO (~(uint64_t)0)

static inline uint64_t
npt_counted_pointer_wire_count(const void *ptr, uint64_t count)
{
    if (!ptr)
        return 0;
    return count ? count : NPT_COUNTED_POINTER_PRESENT_ZERO;
}

static inline bool
npt_decode_counted_pointer_count(struct npt_cs_decoder *dec, uint64_t *count)
{
    uint64_t wire_count = npt_decode_array_count_unchecked(dec);

    if (!wire_count) {
        *count = 0;
        return false;
    }

    *count = wire_count == NPT_COUNTED_POINTER_PRESENT_ZERO
        ? 0 : wire_count;
    return true;
}

/* ------------------------------------------------------------------ */
/* Simple pointer (present = 1, absent = 0)                            */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_simple_pointer(const void *val)
{
    (void)val;
    return npt_sizeof_array_count(val ? 1 : 0);
}

static inline bool npt_encode_simple_pointer(struct npt_cs_encoder *enc,
                                             const void *val)
{
    npt_encode_array_count(enc, val ? 1 : 0);
    return val != NULL;
}

static inline bool npt_decode_simple_pointer(struct npt_cs_decoder *dec)
{
    return npt_decode_array_count_unchecked(dec) != 0;
}

/* ------------------------------------------------------------------ */
/* Wide string (WCHAR = uint16_t) length + encode/decode               */
/* ------------------------------------------------------------------ */

/* Platform-safe WCHAR string length.  WCHAR is always uint16_t (2 bytes)
 * on the wire, but wchar_t may be 4 bytes on Linux.  Scan uint16_t
 * elements directly to get the correct count. */
static inline size_t npt_wcslen(const WCHAR *s)
{
    size_t n = 0;
    while (s[n])
        n++;
    return n;
}

static inline void npt_decode_wchar_array(struct npt_cs_decoder *dec,
                                          WCHAR *val, size_t byte_size)
{
    npt_decode_blob_array(dec, val, byte_size);
    if (byte_size >= sizeof(WCHAR))
        val[byte_size / sizeof(WCHAR) - 1] = 0;
    else if (byte_size)
        npt_cs_decoder_set_fatal(dec);
}

/* ------------------------------------------------------------------ */
/* Null-terminated string (char blob)                                  */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_char_array(const char *val, size_t size)
{
    return npt_sizeof_blob_array(val, size);
}

static inline void npt_encode_char_array(struct npt_cs_encoder *enc,
                                         const char *val, size_t size)
{
    npt_encode_blob_array(enc, val, size);
}

static inline void npt_decode_char_array(struct npt_cs_decoder *dec,
                                         char *val, size_t size)
{
    npt_decode_blob_array(dec, val, size);
    if (size)
        val[size - 1] = '\0';
    else
        npt_cs_decoder_set_fatal(dec);
}

/* ------------------------------------------------------------------ */
/* COM handle encode/decode                                            */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_com_handle(void)
{
    return sizeof(uint64_t);
}

static inline void npt_encode_com_handle(struct npt_cs_encoder *enc,
                                         npt_object_id id)
{
    npt_encode_uint64_t(enc, &id);
}

static inline void npt_decode_com_handle(struct npt_cs_decoder *dec,
                                         npt_object_id *id)
{
    npt_decode_uint64_t(dec, id);
}

/* ------------------------------------------------------------------ */
/* Win32 handle encode/decode                                          */
/* ------------------------------------------------------------------ */

static inline size_t npt_sizeof_win32_handle(void)
{
    return sizeof(uint64_t);
}

static inline void npt_encode_win32_handle(struct npt_cs_encoder *enc,
                                           npt_object_id id)
{
    npt_encode_uint64_t(enc, &id);
}

static inline void npt_decode_win32_handle(struct npt_cs_decoder *dec,
                                           npt_object_id *id)
{
    npt_decode_uint64_t(dec, id);
}

/* ------------------------------------------------------------------ */
/* void * (opaque pointer) encode/decode                               */
/* ------------------------------------------------------------------ */

/* The codegen emits npt_sizeof_void / npt_encode_void / npt_decode_void
 * for void ** output parameters (e.g. ID3D11VideoContext::GetDecoderBuffer's
 * ppBuffer, ID3D12Resource::Map's ppData).  On the wire a void* is
 * represented as a uint64 host-pointer-as-id. */

static inline size_t npt_sizeof_void(const void *val, int max_mode)
{
    return sizeof(uint64_t);
}

static inline void npt_encode_void(struct npt_cs_encoder *enc,
                                   const void *val)
{
    uint64_t id = (uint64_t)(uintptr_t)(*(const void *const *)val);
    npt_encode_uint64_t(enc, &id);
}

static inline void npt_decode_void(struct npt_cs_decoder *dec, void *val)
{
    uint64_t id;
    npt_decode_uint64_t(dec, &id);
    *(void **)val = (void *)(uintptr_t)id;
}

#endif /* NPT_PROTOCOL_COMMON_CS_HELPERS_H */
