/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12resource.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12RESOURCE_H
#define NPT_PROTOCOL_HOST_ID3D12RESOURCE_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12Resource::Map
 */

struct npt_command_ID3D12Resource_Map {
    void *_self;
    UINT Subresource;
    const D3D12_RANGE * pReadRange;
    void ** ppData;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Resource_Map_args_temp(struct npt_cs_decoder *dec,
                                        struct npt_command_ID3D12Resource_Map *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->Subresource);
    if (npt_decode_simple_pointer(dec)) {
        args->pReadRange = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_RANGE));
        if (!args->pReadRange) return;
        npt_decode_D3D12_RANGE(dec, (D3D12_RANGE *)args->pReadRange);
    } else {
        args->pReadRange = NULL;
    }

    /* Allocate temp storage for output-only parameters */


    args->ppData = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
    if (!args->ppData) return;
    *args->ppData = NULL;
}

static inline void
npt_replace_ID3D12Resource_Map_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_Map *args)
{
}

static inline void
npt_encode_ID3D12Resource_Map_reply(struct npt_cs_encoder *enc,
                                    const struct npt_command_ID3D12Resource_Map *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_Map),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->ppData))
        npt_encode_void(enc, args->ppData);
}

static inline void
npt_dispatch_ID3D12Resource_Map(struct npt_dispatch_context *ctx,
                                uint32_t cmd_flags,
                                uint64_t object_id)
{
    struct npt_command_ID3D12Resource_Map args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_Map_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_Map on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_Map_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_Map: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_Map _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_Map, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_Map);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->Map) {
        args.ret = ctx->id3d12resource_dispatch_overrides->Map(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.Subresource, args.pReadRange, args.ppData);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_Map_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::Unmap
 */

struct npt_command_ID3D12Resource_Unmap {
    void *_self;
    UINT Subresource;
    const D3D12_RANGE * pWrittenRange;
};

static inline void
npt_decode_ID3D12Resource_Unmap_args_temp(struct npt_cs_decoder *dec,
                                          struct npt_command_ID3D12Resource_Unmap *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->Subresource);
    if (npt_decode_simple_pointer(dec)) {
        args->pWrittenRange = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_RANGE));
        if (!args->pWrittenRange) return;
        npt_decode_D3D12_RANGE(dec, (D3D12_RANGE *)args->pWrittenRange);
    } else {
        args->pWrittenRange = NULL;
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12Resource_Unmap_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_Unmap *args)
{
}

static inline void
npt_encode_ID3D12Resource_Unmap_reply(struct npt_cs_encoder *enc,
                                      const struct npt_command_ID3D12Resource_Unmap *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_Unmap),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12Resource_Unmap(struct npt_dispatch_context *ctx,
                                  uint32_t cmd_flags,
                                  uint64_t object_id)
{
    struct npt_command_ID3D12Resource_Unmap args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_Unmap_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_Unmap on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_Unmap_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_Unmap: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_Unmap _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_Unmap, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_Unmap);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->Unmap) {
        ctx->id3d12resource_dispatch_overrides->Unmap(ctx, &args, _original);
    } else {
        _original(args._self, args.Subresource, args.pWrittenRange);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_Unmap_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::GetDesc
 */

struct npt_command_ID3D12Resource_GetDesc {
    void *_self;
    D3D12_RESOURCE_DESC ret;
};

static inline void
npt_decode_ID3D12Resource_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                            struct npt_command_ID3D12Resource_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12Resource_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12Resource_GetDesc_reply(struct npt_cs_encoder *enc,
                                        const struct npt_command_ID3D12Resource_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_RESOURCE_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12Resource_GetDesc(struct npt_dispatch_context *ctx,
                                    uint32_t cmd_flags,
                                    uint64_t object_id)
{
    struct npt_command_ID3D12Resource_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetDesc on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_GetDesc_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetDesc: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_GetDesc);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12resource_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::GetGPUVirtualAddress
 */

struct npt_command_ID3D12Resource_GetGPUVirtualAddress {
    void *_self;
    D3D12_GPU_VIRTUAL_ADDRESS ret;
};

static inline void
npt_decode_ID3D12Resource_GetGPUVirtualAddress_args_temp(struct npt_cs_decoder *dec,
                                                         struct npt_command_ID3D12Resource_GetGPUVirtualAddress *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12Resource_GetGPUVirtualAddress_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_GetGPUVirtualAddress *args)
{
}

static inline void
npt_encode_ID3D12Resource_GetGPUVirtualAddress_reply(struct npt_cs_encoder *enc,
                                                     const struct npt_command_ID3D12Resource_GetGPUVirtualAddress *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_GetGPUVirtualAddress),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_GPU_VIRTUAL_ADDRESS(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12Resource_GetGPUVirtualAddress(struct npt_dispatch_context *ctx,
                                                 uint32_t cmd_flags,
                                                 uint64_t object_id)
{
    struct npt_command_ID3D12Resource_GetGPUVirtualAddress args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_GetGPUVirtualAddress_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetGPUVirtualAddress on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_GetGPUVirtualAddress_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetGPUVirtualAddress: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_GetGPUVirtualAddress _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_GetGPUVirtualAddress, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_GetGPUVirtualAddress);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->GetGPUVirtualAddress) {
        args.ret = ctx->id3d12resource_dispatch_overrides->GetGPUVirtualAddress(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_GetGPUVirtualAddress_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::WriteToSubresource
 */

struct npt_command_ID3D12Resource_WriteToSubresource {
    void *_self;
    UINT DstSubresource;
    const D3D12_BOX * pDstBox;
    const void * pSrcData;
    UINT SrcRowPitch;
    UINT SrcDepthPitch;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Resource_WriteToSubresource_args_temp(struct npt_cs_decoder *dec,
                                                       struct npt_command_ID3D12Resource_WriteToSubresource *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->DstSubresource);
    if (npt_decode_simple_pointer(dec)) {
        args->pDstBox = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_BOX));
        if (!args->pDstBox) return;
        npt_decode_D3D12_BOX(dec, (D3D12_BOX *)args->pDstBox);
    } else {
        args->pDstBox = NULL;
    }
    /* ERROR: pSrcData (void) is not serializable */
    return;
    npt_decode_UINT(dec, &args->SrcRowPitch);
    npt_decode_UINT(dec, &args->SrcDepthPitch);
    /* Allocate temp storage for output-only parameters */





}

static inline void
npt_replace_ID3D12Resource_WriteToSubresource_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_WriteToSubresource *args)
{
}

static inline void
npt_encode_ID3D12Resource_WriteToSubresource_reply(struct npt_cs_encoder *enc,
                                                   const struct npt_command_ID3D12Resource_WriteToSubresource *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_WriteToSubresource),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12Resource_WriteToSubresource(struct npt_dispatch_context *ctx,
                                               uint32_t cmd_flags,
                                               uint64_t object_id)
{
    struct npt_command_ID3D12Resource_WriteToSubresource args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_WriteToSubresource_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_WriteToSubresource on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_WriteToSubresource_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_WriteToSubresource: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_WriteToSubresource _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_WriteToSubresource, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_WriteToSubresource);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->WriteToSubresource) {
        args.ret = ctx->id3d12resource_dispatch_overrides->WriteToSubresource(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.DstSubresource, args.pDstBox, args.pSrcData, args.SrcRowPitch, args.SrcDepthPitch);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_WriteToSubresource_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::ReadFromSubresource
 */

struct npt_command_ID3D12Resource_ReadFromSubresource {
    void *_self;
    void * pDstData;
    UINT DstRowPitch;
    UINT DstDepthPitch;
    UINT SrcSubresource;
    const D3D12_BOX * pSrcBox;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Resource_ReadFromSubresource_args_temp(struct npt_cs_decoder *dec,
                                                        struct npt_command_ID3D12Resource_ReadFromSubresource *args)
{
    /* Decode input parameters from the wire */

    npt_decode_UINT(dec, &args->DstRowPitch);
    npt_decode_UINT(dec, &args->DstDepthPitch);
    npt_decode_UINT(dec, &args->SrcSubresource);
    if (npt_decode_simple_pointer(dec)) {
        args->pSrcBox = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_BOX));
        if (!args->pSrcBox) return;
        npt_decode_D3D12_BOX(dec, (D3D12_BOX *)args->pSrcBox);
    } else {
        args->pSrcBox = NULL;
    }
    /* Allocate temp storage for output-only parameters */
    args->pDstData = npt_cs_decoder_alloc_temp(dec, 1);
    if (!args->pDstData) return;
    memset(args->pDstData, 0, 1);




}

static inline void
npt_replace_ID3D12Resource_ReadFromSubresource_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_ReadFromSubresource *args)
{
}

static inline void
npt_encode_ID3D12Resource_ReadFromSubresource_reply(struct npt_cs_encoder *enc,
                                                    const struct npt_command_ID3D12Resource_ReadFromSubresource *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_ReadFromSubresource),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    /* ERROR: pDstData (void) is not serializable */
    return;
}

static inline void
npt_dispatch_ID3D12Resource_ReadFromSubresource(struct npt_dispatch_context *ctx,
                                                uint32_t cmd_flags,
                                                uint64_t object_id)
{
    struct npt_command_ID3D12Resource_ReadFromSubresource args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_ReadFromSubresource_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_ReadFromSubresource on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_ReadFromSubresource_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_ReadFromSubresource: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_ReadFromSubresource _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_ReadFromSubresource, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_ReadFromSubresource);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->ReadFromSubresource) {
        args.ret = ctx->id3d12resource_dispatch_overrides->ReadFromSubresource(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pDstData, args.DstRowPitch, args.DstDepthPitch, args.SrcSubresource, args.pSrcBox);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_ReadFromSubresource_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource::GetHeapProperties
 */

struct npt_command_ID3D12Resource_GetHeapProperties {
    void *_self;
    D3D12_HEAP_PROPERTIES * pHeapProperties;
    D3D12_HEAP_FLAGS * pHeapFlags;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Resource_GetHeapProperties_args_temp(struct npt_cs_decoder *dec,
                                                      struct npt_command_ID3D12Resource_GetHeapProperties *args)
{
    /* Decode input parameters from the wire */


    /* Allocate temp storage for output-only parameters */
    args->pHeapProperties = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_HEAP_PROPERTIES));
    if (!args->pHeapProperties) return;
    memset(args->pHeapProperties, 0, sizeof(D3D12_HEAP_PROPERTIES));
    args->pHeapFlags = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_HEAP_FLAGS));
    if (!args->pHeapFlags) return;
    memset(args->pHeapFlags, 0, sizeof(D3D12_HEAP_FLAGS));
}

static inline void
npt_replace_ID3D12Resource_GetHeapProperties_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource_GetHeapProperties *args)
{
}

static inline void
npt_encode_ID3D12Resource_GetHeapProperties_reply(struct npt_cs_encoder *enc,
                                                  const struct npt_command_ID3D12Resource_GetHeapProperties *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource,
                                 NPT_METHOD_ID3D12Resource_GetHeapProperties),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pHeapProperties))
        npt_encode_D3D12_HEAP_PROPERTIES(enc, args->pHeapProperties);
    if (npt_encode_simple_pointer(enc, args->pHeapFlags))
        npt_encode_D3D12_HEAP_FLAGS(enc, args->pHeapFlags);
}

static inline void
npt_dispatch_ID3D12Resource_GetHeapProperties(struct npt_dispatch_context *ctx,
                                              uint32_t cmd_flags,
                                              uint64_t object_id)
{
    struct npt_command_ID3D12Resource_GetHeapProperties args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource_GetHeapProperties_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetHeapProperties on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource_GetHeapProperties_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource_GetHeapProperties: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource_GetHeapProperties _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource_GetHeapProperties, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource_GetHeapProperties);

    if (ctx->id3d12resource_dispatch_overrides && ctx->id3d12resource_dispatch_overrides->GetHeapProperties) {
        args.ret = ctx->id3d12resource_dispatch_overrides->GetHeapProperties(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pHeapProperties, args.pHeapFlags);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource_GetHeapProperties_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource1::GetProtectedResourceSession
 */

struct npt_command_ID3D12Resource1_GetProtectedResourceSession {
    void *_self;
    const IID * riid;
    void ** ppProtectedSession;
    /* Shadow: the guest-allocated id for ppProtectedSession arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppProtectedSession -> *ppProtectedSession} in the
     * context object table. */
    uint64_t _guest_id_ppProtectedSession;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12Resource1_GetProtectedResourceSession_args_temp(struct npt_cs_decoder *dec,
                                                                 struct npt_command_ID3D12Resource1_GetProtectedResourceSession *args)
{
    /* Decode input parameters from the wire */
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppProtectedSession = _gid;
        args->ppProtectedSession = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppProtectedSession) return;
        *args->ppProtectedSession = NULL;
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12Resource1_GetProtectedResourceSession_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource1_GetProtectedResourceSession *args)
{
}

static inline void
npt_encode_ID3D12Resource1_GetProtectedResourceSession_reply(struct npt_cs_encoder *enc,
                                                             const struct npt_command_ID3D12Resource1_GetProtectedResourceSession *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource1,
                                 NPT_METHOD_ID3D12Resource1_GetProtectedResourceSession),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppProtectedSession (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12Resource1_GetProtectedResourceSession(struct npt_dispatch_context *ctx,
                                                         uint32_t cmd_flags,
                                                         uint64_t object_id)
{
    struct npt_command_ID3D12Resource1_GetProtectedResourceSession args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource1_GetProtectedResourceSession_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource1_GetProtectedResourceSession on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppProtectedSession);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource1_GetProtectedResourceSession_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource1_GetProtectedResourceSession: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppProtectedSession);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource1_GetProtectedResourceSession _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource1_GetProtectedResourceSession, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource1_GetProtectedResourceSession);

    if (ctx->id3d12resource1_dispatch_overrides && ctx->id3d12resource1_dispatch_overrides->GetProtectedResourceSession) {
        args.ret = ctx->id3d12resource1_dispatch_overrides->GetProtectedResourceSession(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.riid, args.ppProtectedSession);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppProtectedSession && *args.ppProtectedSession)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppProtectedSession, *args.ppProtectedSession,
            npt_object_type_from_iid(args.riid));
    else if (args.ppProtectedSession)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppProtectedSession);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource1_GetProtectedResourceSession_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12Resource2::GetDesc1
 */

struct npt_command_ID3D12Resource2_GetDesc1 {
    void *_self;
    D3D12_RESOURCE_DESC1 ret;
};

static inline void
npt_decode_ID3D12Resource2_GetDesc1_args_temp(struct npt_cs_decoder *dec,
                                              struct npt_command_ID3D12Resource2_GetDesc1 *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12Resource2_GetDesc1_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12Resource2_GetDesc1 *args)
{
}

static inline void
npt_encode_ID3D12Resource2_GetDesc1_reply(struct npt_cs_encoder *enc,
                                          const struct npt_command_ID3D12Resource2_GetDesc1 *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12Resource2,
                                 NPT_METHOD_ID3D12Resource2_GetDesc1),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_RESOURCE_DESC1(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12Resource2_GetDesc1(struct npt_dispatch_context *ctx,
                                      uint32_t cmd_flags,
                                      uint64_t object_id)
{
    struct npt_command_ID3D12Resource2_GetDesc1 args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12Resource2_GetDesc1_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12RESOURCE2);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource2_GetDesc1 on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12Resource2_GetDesc1_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12Resource2_GetDesc1: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12Resource2_GetDesc1 _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12Resource2_GetDesc1, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12Resource2_GetDesc1);

    if (ctx->id3d12resource2_dispatch_overrides && ctx->id3d12resource2_dispatch_overrides->GetDesc1) {
        args.ret = ctx->id3d12resource2_dispatch_overrides->GetDesc1(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12Resource2_GetDesc1_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12RESOURCE_H */
