/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12sdkconfiguration.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12SDKCONFIGURATION_H
#define NPT_PROTOCOL_HOST_ID3D12SDKCONFIGURATION_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12SDKConfiguration::SetSDKVersion
 */

struct npt_command_ID3D12SDKConfiguration_SetSDKVersion {
    void *_self;
    UINT SDKVersion;
    const CHAR * SDKPath;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12SDKConfiguration_SetSDKVersion_args_temp(struct npt_cs_decoder *dec,
                                                          struct npt_command_ID3D12SDKConfiguration_SetSDKVersion *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->SDKVersion);
    {
        const uint64_t _str_size = npt_decode_array_count_unchecked(dec);
        if (_str_size) {
            args->SDKPath = npt_cs_decoder_alloc_temp(dec, _str_size);
            if (!args->SDKPath) return;
            npt_decode_char_array(dec, (char *)args->SDKPath, _str_size);
        } else {
            args->SDKPath = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_ID3D12SDKConfiguration_SetSDKVersion_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12SDKConfiguration_SetSDKVersion *args)
{
}

static inline void
npt_encode_ID3D12SDKConfiguration_SetSDKVersion_reply(struct npt_cs_encoder *enc,
                                                      const struct npt_command_ID3D12SDKConfiguration_SetSDKVersion *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12SDKConfiguration,
                                 NPT_METHOD_ID3D12SDKConfiguration_SetSDKVersion),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12SDKConfiguration_SetSDKVersion(struct npt_dispatch_context *ctx,
                                                  uint32_t cmd_flags,
                                                  uint64_t object_id)
{
    struct npt_command_ID3D12SDKConfiguration_SetSDKVersion args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12SDKConfiguration_SetSDKVersion_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12SDKCONFIGURATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration_SetSDKVersion on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12SDKConfiguration_SetSDKVersion_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration_SetSDKVersion: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12SDKConfiguration_SetSDKVersion _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12SDKConfiguration_SetSDKVersion, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12SDKConfiguration_SetSDKVersion);

    if (ctx->id3d12sdkconfiguration_dispatch_overrides && ctx->id3d12sdkconfiguration_dispatch_overrides->SetSDKVersion) {
        args.ret = ctx->id3d12sdkconfiguration_dispatch_overrides->SetSDKVersion(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.SDKVersion, args.SDKPath);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12SDKConfiguration_SetSDKVersion_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12SDKConfiguration1::CreateDeviceFactory
 */

struct npt_command_ID3D12SDKConfiguration1_CreateDeviceFactory {
    void *_self;
    UINT SDKVersion;
    const CHAR * SDKPath;
    const IID * riid;
    void ** ppvFactory;
    /* Shadow: the guest-allocated id for ppvFactory arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppvFactory -> *ppvFactory} in the
     * context object table. */
    uint64_t _guest_id_ppvFactory;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12SDKConfiguration1_CreateDeviceFactory_args_temp(struct npt_cs_decoder *dec,
                                                                 struct npt_command_ID3D12SDKConfiguration1_CreateDeviceFactory *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->SDKVersion);
    {
        const uint64_t _str_size = npt_decode_array_count_unchecked(dec);
        if (_str_size) {
            args->SDKPath = npt_cs_decoder_alloc_temp(dec, _str_size);
            if (!args->SDKPath) return;
            npt_decode_char_array(dec, (char *)args->SDKPath, _str_size);
        } else {
            args->SDKPath = NULL;
        }
    }
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppvFactory = _gid;
        args->ppvFactory = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppvFactory) return;
        *args->ppvFactory = NULL;
    }
    /* Allocate temp storage for output-only parameters */




}

static inline void
npt_replace_ID3D12SDKConfiguration1_CreateDeviceFactory_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12SDKConfiguration1_CreateDeviceFactory *args)
{
}

static inline void
npt_encode_ID3D12SDKConfiguration1_CreateDeviceFactory_reply(struct npt_cs_encoder *enc,
                                                             const struct npt_command_ID3D12SDKConfiguration1_CreateDeviceFactory *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12SDKConfiguration1,
                                 NPT_METHOD_ID3D12SDKConfiguration1_CreateDeviceFactory),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppvFactory (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12SDKConfiguration1_CreateDeviceFactory(struct npt_dispatch_context *ctx,
                                                         uint32_t cmd_flags,
                                                         uint64_t object_id)
{
    struct npt_command_ID3D12SDKConfiguration1_CreateDeviceFactory args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12SDKConfiguration1_CreateDeviceFactory_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12SDKCONFIGURATION1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration1_CreateDeviceFactory on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12SDKConfiguration1_CreateDeviceFactory_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration1_CreateDeviceFactory: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12SDKConfiguration1_CreateDeviceFactory _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12SDKConfiguration1_CreateDeviceFactory, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12SDKConfiguration1_CreateDeviceFactory);

    if (ctx->id3d12sdkconfiguration1_dispatch_overrides && ctx->id3d12sdkconfiguration1_dispatch_overrides->CreateDeviceFactory) {
        args.ret = ctx->id3d12sdkconfiguration1_dispatch_overrides->CreateDeviceFactory(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.SDKVersion, args.SDKPath, args.riid, args.ppvFactory);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppvFactory && *args.ppvFactory)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppvFactory, *args.ppvFactory,
            npt_object_type_from_iid(args.riid));

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12SDKConfiguration1_CreateDeviceFactory_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12SDKConfiguration1::FreeUnusedSDKs
 */

struct npt_command_ID3D12SDKConfiguration1_FreeUnusedSDKs {
    void *_self;
};

static inline void
npt_decode_ID3D12SDKConfiguration1_FreeUnusedSDKs_args_temp(struct npt_cs_decoder *dec,
                                                            struct npt_command_ID3D12SDKConfiguration1_FreeUnusedSDKs *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12SDKConfiguration1_FreeUnusedSDKs_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12SDKConfiguration1_FreeUnusedSDKs *args)
{
}

static inline void
npt_encode_ID3D12SDKConfiguration1_FreeUnusedSDKs_reply(struct npt_cs_encoder *enc,
                                                        const struct npt_command_ID3D12SDKConfiguration1_FreeUnusedSDKs *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12SDKConfiguration1,
                                 NPT_METHOD_ID3D12SDKConfiguration1_FreeUnusedSDKs),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12SDKConfiguration1_FreeUnusedSDKs(struct npt_dispatch_context *ctx,
                                                    uint32_t cmd_flags,
                                                    uint64_t object_id)
{
    struct npt_command_ID3D12SDKConfiguration1_FreeUnusedSDKs args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12SDKConfiguration1_FreeUnusedSDKs_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12SDKCONFIGURATION1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration1_FreeUnusedSDKs on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12SDKConfiguration1_FreeUnusedSDKs_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12SDKConfiguration1_FreeUnusedSDKs: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12SDKConfiguration1_FreeUnusedSDKs _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12SDKConfiguration1_FreeUnusedSDKs, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12SDKConfiguration1_FreeUnusedSDKs);

    if (ctx->id3d12sdkconfiguration1_dispatch_overrides && ctx->id3d12sdkconfiguration1_dispatch_overrides->FreeUnusedSDKs) {
        ctx->id3d12sdkconfiguration1_dispatch_overrides->FreeUnusedSDKs(ctx, &args, _original);
    } else {
        _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12SDKConfiguration1_FreeUnusedSDKs_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12SDKCONFIGURATION_H */
