/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12deviceconfiguration.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12DEVICECONFIGURATION_H
#define NPT_PROTOCOL_HOST_ID3D12DEVICECONFIGURATION_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12DeviceConfiguration::GetDesc
 */

struct npt_command_ID3D12DeviceConfiguration_GetDesc {
    void *_self;
    D3D12_DEVICE_CONFIGURATION_DESC ret;
};

static inline void
npt_decode_ID3D12DeviceConfiguration_GetDesc_args_temp(struct npt_cs_decoder *dec,
                                                       struct npt_command_ID3D12DeviceConfiguration_GetDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12DeviceConfiguration_GetDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceConfiguration_GetDesc *args)
{
}

static inline void
npt_encode_ID3D12DeviceConfiguration_GetDesc_reply(struct npt_cs_encoder *enc,
                                                   const struct npt_command_ID3D12DeviceConfiguration_GetDesc *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceConfiguration,
                                 NPT_METHOD_ID3D12DeviceConfiguration_GetDesc),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_DEVICE_CONFIGURATION_DESC(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12DeviceConfiguration_GetDesc(struct npt_dispatch_context *ctx,
                                               uint32_t cmd_flags,
                                               uint64_t object_id)
{
    struct npt_command_ID3D12DeviceConfiguration_GetDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceConfiguration_GetDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICECONFIGURATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_GetDesc on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceConfiguration_GetDesc_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_GetDesc: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceConfiguration_GetDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceConfiguration_GetDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceConfiguration_GetDesc);

    if (ctx->id3d12deviceconfiguration_dispatch_overrides && ctx->id3d12deviceconfiguration_dispatch_overrides->GetDesc) {
        args.ret = ctx->id3d12deviceconfiguration_dispatch_overrides->GetDesc(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceConfiguration_GetDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceConfiguration::GetEnabledExperimentalFeatures
 */

struct npt_command_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures {
    void *_self;
    GUID * pGuids;
    UINT NumGuids;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_args_temp(struct npt_cs_decoder *dec,
                                                                              struct npt_command_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures *args)
{
    /* Decode input parameters from the wire */

    npt_decode_UINT(dec, &args->NumGuids);
    /* Allocate temp storage for output-only parameters */
    if (args->NumGuids) {
        args->pGuids = npt_cs_decoder_alloc_temp_array(dec, sizeof(GUID), args->NumGuids);
        if (!args->pGuids) return;
        memset(args->pGuids, 0, sizeof(GUID) * args->NumGuids);
    } else {
        args->pGuids = NULL;
    }

}

static inline void
npt_replace_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures *args)
{
}

static inline void
npt_encode_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_reply(struct npt_cs_encoder *enc,
                                                                          const struct npt_command_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceConfiguration,
                                 NPT_METHOD_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (args->pGuids) {
        npt_encode_array_count(enc, args->NumGuids);
        for (uint32_t _i = 0; _i < (uint32_t)(args->NumGuids); _i++)
            npt_encode_GUID(enc, &args->pGuids[_i]);
    } else {
        npt_encode_array_count(enc, 0);
    }
}

static inline void
npt_dispatch_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures(struct npt_dispatch_context *ctx,
                                                                      uint32_t cmd_flags,
                                                                      uint64_t object_id)
{
    struct npt_command_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICECONFIGURATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures);

    if (ctx->id3d12deviceconfiguration_dispatch_overrides && ctx->id3d12deviceconfiguration_dispatch_overrides->GetEnabledExperimentalFeatures) {
        args.ret = ctx->id3d12deviceconfiguration_dispatch_overrides->GetEnabledExperimentalFeatures(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pGuids, args.NumGuids);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceConfiguration_GetEnabledExperimentalFeatures_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceConfiguration::SerializeVersionedRootSignature
 */

struct npt_command_ID3D12DeviceConfiguration_SerializeVersionedRootSignature {
    void *_self;
    const D3D12_VERSIONED_ROOT_SIGNATURE_DESC * pDesc;
    ID3DBlob ** ppResult;
    ID3DBlob ** ppError;
    /* Shadow: the guest-allocated id for ppResult arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppResult -> *ppResult} in the
     * context object table. */
    uint64_t _guest_id_ppResult;
    /* Shadow: the guest-allocated id for ppError arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppError -> *ppError} in the
     * context object table. */
    uint64_t _guest_id_ppError;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_args_temp(struct npt_cs_decoder *dec,
                                                                               struct npt_command_ID3D12DeviceConfiguration_SerializeVersionedRootSignature *args)
{
    /* Decode input parameters from the wire */
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_VERSIONED_ROOT_SIGNATURE_DESC));
        if (!args->pDesc) return;
        npt_decode_D3D12_VERSIONED_ROOT_SIGNATURE_DESC(dec, (D3D12_VERSIONED_ROOT_SIGNATURE_DESC *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppResult = _gid;
        args->ppResult = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppResult) return;
        *args->ppResult = NULL;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppError = _gid;
        args->ppError = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppError) return;
        *args->ppError = NULL;
    }
    /* Allocate temp storage for output-only parameters */



}

static inline void
npt_replace_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceConfiguration_SerializeVersionedRootSignature *args)
{
}

static inline void
npt_encode_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_reply(struct npt_cs_encoder *enc,
                                                                           const struct npt_command_ID3D12DeviceConfiguration_SerializeVersionedRootSignature *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceConfiguration,
                                 NPT_METHOD_ID3D12DeviceConfiguration_SerializeVersionedRootSignature),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppResult (guest-allocated id, registered host-side; not in reply) */
/* skip args->ppError (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12DeviceConfiguration_SerializeVersionedRootSignature(struct npt_dispatch_context *ctx,
                                                                       uint32_t cmd_flags,
                                                                       uint64_t object_id)
{
    struct npt_command_ID3D12DeviceConfiguration_SerializeVersionedRootSignature args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICECONFIGURATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_SerializeVersionedRootSignature on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppResult);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppError);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_SerializeVersionedRootSignature: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppResult);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppError);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceConfiguration_SerializeVersionedRootSignature _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceConfiguration_SerializeVersionedRootSignature, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceConfiguration_SerializeVersionedRootSignature);

    if (ctx->id3d12deviceconfiguration_dispatch_overrides && ctx->id3d12deviceconfiguration_dispatch_overrides->SerializeVersionedRootSignature) {
        args.ret = ctx->id3d12deviceconfiguration_dispatch_overrides->SerializeVersionedRootSignature(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pDesc, args.ppResult, args.ppError);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppResult && *args.ppResult)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppResult, *args.ppResult, NPT_OBJECT_TYPE_ID3D10BLOB);
    else if (args.ppResult)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppResult);
    if (args.ppError && *args.ppError)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppError, *args.ppError, NPT_OBJECT_TYPE_ID3D10BLOB);
    else if (args.ppError)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppError);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceConfiguration_SerializeVersionedRootSignature_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceConfiguration::CreateVersionedRootSignatureDeserializer
 */

struct npt_command_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer {
    void *_self;
    const void * pBlob;
    SIZE_T Size;
    const IID * riid;
    void ** ppvDeserializer;
    /* Shadow: the guest-allocated id for ppvDeserializer arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppvDeserializer -> *ppvDeserializer} in the
     * context object table. */
    uint64_t _guest_id_ppvDeserializer;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_args_temp(struct npt_cs_decoder *dec,
                                                                                        struct npt_command_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _blob_size = npt_decode_array_count_unchecked(dec);
        if (_blob_size) {
            args->pBlob = npt_cs_decoder_alloc_temp(dec, _blob_size);
            if (!args->pBlob) return;
            npt_decode_blob_array(dec, (void *)args->pBlob, _blob_size);
        } else {
            args->pBlob = NULL;
        }
    }
    npt_decode_SIZE_T(dec, &args->Size);
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppvDeserializer = _gid;
        args->ppvDeserializer = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppvDeserializer) return;
        *args->ppvDeserializer = NULL;
    }
    /* Allocate temp storage for output-only parameters */




}

static inline void
npt_replace_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer *args)
{
}

static inline void
npt_encode_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_reply(struct npt_cs_encoder *enc,
                                                                                    const struct npt_command_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceConfiguration,
                                 NPT_METHOD_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppvDeserializer (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer(struct npt_dispatch_context *ctx,
                                                                                uint32_t cmd_flags,
                                                                                uint64_t object_id)
{
    struct npt_command_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICECONFIGURATION);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer);

    if (ctx->id3d12deviceconfiguration_dispatch_overrides && ctx->id3d12deviceconfiguration_dispatch_overrides->CreateVersionedRootSignatureDeserializer) {
        args.ret = ctx->id3d12deviceconfiguration_dispatch_overrides->CreateVersionedRootSignatureDeserializer(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pBlob, args.Size, args.riid, args.ppvDeserializer);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppvDeserializer && *args.ppvDeserializer)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppvDeserializer, *args.ppvDeserializer,
            npt_object_type_from_iid(args.riid));
    else if (args.ppvDeserializer)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceConfiguration_CreateVersionedRootSignatureDeserializer_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceConfiguration1::CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary
 */

struct npt_command_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary {
    void *_self;
    const void * pLibraryBlob;
    SIZE_T Size;
    const WCHAR * RootSignatureSubobjectName;
    const IID * riid;
    void ** ppvDeserializer;
    /* Shadow: the guest-allocated id for ppvDeserializer arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppvDeserializer -> *ppvDeserializer} in the
     * context object table. */
    uint64_t _guest_id_ppvDeserializer;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_args_temp(struct npt_cs_decoder *dec,
                                                                                                               struct npt_command_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _blob_size = npt_decode_array_count_unchecked(dec);
        if (_blob_size) {
            args->pLibraryBlob = npt_cs_decoder_alloc_temp(dec, _blob_size);
            if (!args->pLibraryBlob) return;
            npt_decode_blob_array(dec, (void *)args->pLibraryBlob, _blob_size);
        } else {
            args->pLibraryBlob = NULL;
        }
    }
    npt_decode_SIZE_T(dec, &args->Size);
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->RootSignatureSubobjectName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->RootSignatureSubobjectName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->RootSignatureSubobjectName, _wstr_size);
        } else {
            args->RootSignatureSubobjectName = NULL;
        }
    }
    if (npt_decode_simple_pointer(dec)) {
        args->riid = npt_cs_decoder_alloc_temp(dec, sizeof(IID));
        if (!args->riid) return;
        npt_decode_IID(dec, (IID *)args->riid);
    } else {
        args->riid = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppvDeserializer = _gid;
        args->ppvDeserializer = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppvDeserializer) return;
        *args->ppvDeserializer = NULL;
    }
    /* Allocate temp storage for output-only parameters */





}

static inline void
npt_replace_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary *args)
{
}

static inline void
npt_encode_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_reply(struct npt_cs_encoder *enc,
                                                                                                           const struct npt_command_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceConfiguration1,
                                 NPT_METHOD_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppvDeserializer (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary(struct npt_dispatch_context *ctx,
                                                                                                       uint32_t cmd_flags,
                                                                                                       uint64_t object_id)
{
    struct npt_command_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICECONFIGURATION1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary);

    if (ctx->id3d12deviceconfiguration1_dispatch_overrides && ctx->id3d12deviceconfiguration1_dispatch_overrides->CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary) {
        args.ret = ctx->id3d12deviceconfiguration1_dispatch_overrides->CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pLibraryBlob, args.Size, args.RootSignatureSubobjectName, args.riid, args.ppvDeserializer);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppvDeserializer && *args.ppvDeserializer)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppvDeserializer, *args.ppvDeserializer,
            npt_object_type_from_iid(args.riid));
    else if (args.ppvDeserializer)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppvDeserializer);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceConfiguration1_CreateVersionedRootSignatureDeserializerFromSubobjectInLibrary_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12DEVICECONFIGURATION_H */
