/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for idxgifactorymedia.
 */

#ifndef NPT_PROTOCOL_HOST_IDXGIFACTORYMEDIA_H
#define NPT_PROTOCOL_HOST_IDXGIFACTORYMEDIA_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * IDXGIFactoryMedia::CreateSwapChainForCompositionSurfaceHandle
 */

struct npt_command_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle {
    void *_self;
    IUnknown * pDevice;
    HANDLE hSurface;
    const DXGI_SWAP_CHAIN_DESC1 * pDesc;
    IDXGIOutput * pRestrictToOutput;
    IDXGISwapChain1 ** ppSwapChain;
    /* Shadow: the guest-allocated id for ppSwapChain arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppSwapChain -> *ppSwapChain} in the
     * context object table. */
    uint64_t _guest_id_ppSwapChain;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_args_temp(struct npt_cs_decoder *dec,
                                                                                  struct npt_command_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pDevice = (IUnknown *)npt_object_from_id(_id);
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->hSurface = (HANDLE)(uintptr_t)npt_win32_handle_from_id(_id);
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_SWAP_CHAIN_DESC1));
        if (!args->pDesc) return;
        npt_decode_DXGI_SWAP_CHAIN_DESC1(dec, (DXGI_SWAP_CHAIN_DESC1 *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pRestrictToOutput = (IDXGIOutput *)npt_object_from_id(_id);
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppSwapChain = _gid;
        args->ppSwapChain = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppSwapChain) return;
        *args->ppSwapChain = NULL;
    }
    /* Allocate temp storage for output-only parameters */





}

static inline void
npt_replace_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle *args)
{
    args->pDevice = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pDevice, NPT_OBJECT_TYPE_IUNKNOWN);
    args->hSurface = (HANDLE)(uintptr_t)npt_win32_handle_replace(ctx, (npt_object_id)args->hSurface);
    args->pRestrictToOutput = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pRestrictToOutput, NPT_OBJECT_TYPE_IDXGIOUTPUT);
}

static inline void
npt_encode_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_reply(struct npt_cs_encoder *enc,
                                                                              const struct npt_command_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIFactoryMedia,
                                 NPT_METHOD_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppSwapChain (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle(struct npt_dispatch_context *ctx,
                                                                          uint32_t cmd_flags,
                                                                          uint64_t object_id)
{
    struct npt_command_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIFACTORYMEDIA);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle);

    if (ctx->idxgifactorymedia_dispatch_overrides && ctx->idxgifactorymedia_dispatch_overrides->CreateSwapChainForCompositionSurfaceHandle) {
        args.ret = ctx->idxgifactorymedia_dispatch_overrides->CreateSwapChainForCompositionSurfaceHandle(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pDevice, args.hSurface, args.pDesc, args.pRestrictToOutput, args.ppSwapChain);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppSwapChain && *args.ppSwapChain)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppSwapChain, *args.ppSwapChain, NPT_OBJECT_TYPE_IDXGISWAPCHAIN1);
    else if (args.ppSwapChain)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIFactoryMedia_CreateSwapChainForCompositionSurfaceHandle_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIFactoryMedia::CreateDecodeSwapChainForCompositionSurfaceHandle
 */

struct npt_command_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle {
    void *_self;
    IUnknown * pDevice;
    HANDLE hSurface;
    DXGI_DECODE_SWAP_CHAIN_DESC * pDesc;
    IDXGIResource * pYuvDecodeBuffers;
    IDXGIOutput * pRestrictToOutput;
    IDXGIDecodeSwapChain ** ppSwapChain;
    /* Shadow: the guest-allocated id for ppSwapChain arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppSwapChain -> *ppSwapChain} in the
     * context object table. */
    uint64_t _guest_id_ppSwapChain;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_args_temp(struct npt_cs_decoder *dec,
                                                                                        struct npt_command_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle *args)
{
    /* Decode input parameters from the wire */
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pDevice = (IUnknown *)npt_object_from_id(_id);
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->hSurface = (HANDLE)(uintptr_t)npt_win32_handle_from_id(_id);
    }
    if (npt_decode_simple_pointer(dec)) {
        args->pDesc = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_DECODE_SWAP_CHAIN_DESC));
        if (!args->pDesc) return;
        npt_decode_DXGI_DECODE_SWAP_CHAIN_DESC(dec, (DXGI_DECODE_SWAP_CHAIN_DESC *)args->pDesc);
    } else {
        args->pDesc = NULL;
        npt_cs_decoder_set_fatal(dec); /* non-optional pointer is NULL */
        return;
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pYuvDecodeBuffers = (IDXGIResource *)npt_object_from_id(_id);
    }
    {
        npt_object_id _id;
        npt_decode_uint64_t(dec, &_id);
        args->pRestrictToOutput = (IDXGIOutput *)npt_object_from_id(_id);
    }
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppSwapChain = _gid;
        args->ppSwapChain = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppSwapChain) return;
        *args->ppSwapChain = NULL;
    }
    /* Allocate temp storage for output-only parameters */






}

static inline void
npt_replace_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle *args)
{
    args->pDevice = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pDevice, NPT_OBJECT_TYPE_IUNKNOWN);
    args->hSurface = (HANDLE)(uintptr_t)npt_win32_handle_replace(ctx, (npt_object_id)args->hSurface);
    args->pYuvDecodeBuffers = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pYuvDecodeBuffers, NPT_OBJECT_TYPE_IDXGIRESOURCE);
    args->pRestrictToOutput = npt_cs_handle_lookup(ctx, (npt_object_id)(uintptr_t)args->pRestrictToOutput, NPT_OBJECT_TYPE_IDXGIOUTPUT);
}

static inline void
npt_encode_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_reply(struct npt_cs_encoder *enc,
                                                                                    const struct npt_command_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIFactoryMedia,
                                 NPT_METHOD_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppSwapChain (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle(struct npt_dispatch_context *ctx,
                                                                                uint32_t cmd_flags,
                                                                                uint64_t object_id)
{
    struct npt_command_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIFACTORYMEDIA);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle);

    if (ctx->idxgifactorymedia_dispatch_overrides && ctx->idxgifactorymedia_dispatch_overrides->CreateDecodeSwapChainForCompositionSurfaceHandle) {
        args.ret = ctx->idxgifactorymedia_dispatch_overrides->CreateDecodeSwapChainForCompositionSurfaceHandle(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pDevice, args.hSurface, args.pDesc, args.pYuvDecodeBuffers, args.pRestrictToOutput, args.ppSwapChain);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppSwapChain && *args.ppSwapChain)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppSwapChain, *args.ppSwapChain, NPT_OBJECT_TYPE_IDXGIDECODESWAPCHAIN);
    else if (args.ppSwapChain)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSwapChain);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIFactoryMedia_CreateDecodeSwapChainForCompositionSurfaceHandle_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_IDXGIFACTORYMEDIA_H */
