/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12stateobjectproperties.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12STATEOBJECTPROPERTIES_H
#define NPT_PROTOCOL_HOST_ID3D12STATEOBJECTPROPERTIES_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12StateObjectProperties::GetShaderIdentifier
 */

struct npt_command_ID3D12StateObjectProperties_GetShaderIdentifier {
    void *_self;
    const WCHAR * pExportName;
};

static inline void
npt_decode_ID3D12StateObjectProperties_GetShaderIdentifier_args_temp(struct npt_cs_decoder *dec,
                                                                     struct npt_command_ID3D12StateObjectProperties_GetShaderIdentifier *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pExportName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pExportName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pExportName, _wstr_size);
        } else {
            args->pExportName = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12StateObjectProperties_GetShaderIdentifier_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12StateObjectProperties_GetShaderIdentifier *args)
{
}

static inline void
npt_encode_ID3D12StateObjectProperties_GetShaderIdentifier_reply(struct npt_cs_encoder *enc,
                                                                 const struct npt_command_ID3D12StateObjectProperties_GetShaderIdentifier *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12StateObjectProperties,
                                 NPT_METHOD_ID3D12StateObjectProperties_GetShaderIdentifier),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12StateObjectProperties_GetShaderIdentifier(struct npt_dispatch_context *ctx,
                                                             uint32_t cmd_flags,
                                                             uint64_t object_id)
{
    struct npt_command_ID3D12StateObjectProperties_GetShaderIdentifier args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12StateObjectProperties_GetShaderIdentifier_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12STATEOBJECTPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetShaderIdentifier on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12StateObjectProperties_GetShaderIdentifier_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetShaderIdentifier: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12StateObjectProperties_GetShaderIdentifier _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12StateObjectProperties_GetShaderIdentifier, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12StateObjectProperties_GetShaderIdentifier);

    if (ctx->id3d12stateobjectproperties_dispatch_overrides && ctx->id3d12stateobjectproperties_dispatch_overrides->GetShaderIdentifier) {
        ctx->id3d12stateobjectproperties_dispatch_overrides->GetShaderIdentifier(ctx, &args, _original);
    } else {
        _original(args._self, args.pExportName);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12StateObjectProperties_GetShaderIdentifier_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12StateObjectProperties::GetShaderStackSize
 */

struct npt_command_ID3D12StateObjectProperties_GetShaderStackSize {
    void *_self;
    const WCHAR * pExportName;
    UINT64 ret;
};

static inline void
npt_decode_ID3D12StateObjectProperties_GetShaderStackSize_args_temp(struct npt_cs_decoder *dec,
                                                                    struct npt_command_ID3D12StateObjectProperties_GetShaderStackSize *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pExportName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pExportName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pExportName, _wstr_size);
        } else {
            args->pExportName = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12StateObjectProperties_GetShaderStackSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12StateObjectProperties_GetShaderStackSize *args)
{
}

static inline void
npt_encode_ID3D12StateObjectProperties_GetShaderStackSize_reply(struct npt_cs_encoder *enc,
                                                                const struct npt_command_ID3D12StateObjectProperties_GetShaderStackSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12StateObjectProperties,
                                 NPT_METHOD_ID3D12StateObjectProperties_GetShaderStackSize),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_UINT64(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12StateObjectProperties_GetShaderStackSize(struct npt_dispatch_context *ctx,
                                                            uint32_t cmd_flags,
                                                            uint64_t object_id)
{
    struct npt_command_ID3D12StateObjectProperties_GetShaderStackSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12StateObjectProperties_GetShaderStackSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12STATEOBJECTPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetShaderStackSize on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12StateObjectProperties_GetShaderStackSize_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetShaderStackSize: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12StateObjectProperties_GetShaderStackSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12StateObjectProperties_GetShaderStackSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12StateObjectProperties_GetShaderStackSize);

    if (ctx->id3d12stateobjectproperties_dispatch_overrides && ctx->id3d12stateobjectproperties_dispatch_overrides->GetShaderStackSize) {
        args.ret = ctx->id3d12stateobjectproperties_dispatch_overrides->GetShaderStackSize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pExportName);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12StateObjectProperties_GetShaderStackSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12StateObjectProperties::GetPipelineStackSize
 */

struct npt_command_ID3D12StateObjectProperties_GetPipelineStackSize {
    void *_self;
    UINT64 ret;
};

static inline void
npt_decode_ID3D12StateObjectProperties_GetPipelineStackSize_args_temp(struct npt_cs_decoder *dec,
                                                                      struct npt_command_ID3D12StateObjectProperties_GetPipelineStackSize *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12StateObjectProperties_GetPipelineStackSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12StateObjectProperties_GetPipelineStackSize *args)
{
}

static inline void
npt_encode_ID3D12StateObjectProperties_GetPipelineStackSize_reply(struct npt_cs_encoder *enc,
                                                                  const struct npt_command_ID3D12StateObjectProperties_GetPipelineStackSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12StateObjectProperties,
                                 NPT_METHOD_ID3D12StateObjectProperties_GetPipelineStackSize),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_UINT64(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12StateObjectProperties_GetPipelineStackSize(struct npt_dispatch_context *ctx,
                                                              uint32_t cmd_flags,
                                                              uint64_t object_id)
{
    struct npt_command_ID3D12StateObjectProperties_GetPipelineStackSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12StateObjectProperties_GetPipelineStackSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12STATEOBJECTPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetPipelineStackSize on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12StateObjectProperties_GetPipelineStackSize_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_GetPipelineStackSize: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12StateObjectProperties_GetPipelineStackSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12StateObjectProperties_GetPipelineStackSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12StateObjectProperties_GetPipelineStackSize);

    if (ctx->id3d12stateobjectproperties_dispatch_overrides && ctx->id3d12stateobjectproperties_dispatch_overrides->GetPipelineStackSize) {
        args.ret = ctx->id3d12stateobjectproperties_dispatch_overrides->GetPipelineStackSize(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12StateObjectProperties_GetPipelineStackSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12StateObjectProperties::SetPipelineStackSize
 */

struct npt_command_ID3D12StateObjectProperties_SetPipelineStackSize {
    void *_self;
    UINT64 PipelineStackSizeInBytes;
};

static inline void
npt_decode_ID3D12StateObjectProperties_SetPipelineStackSize_args_temp(struct npt_cs_decoder *dec,
                                                                      struct npt_command_ID3D12StateObjectProperties_SetPipelineStackSize *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT64(dec, &args->PipelineStackSizeInBytes);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12StateObjectProperties_SetPipelineStackSize_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12StateObjectProperties_SetPipelineStackSize *args)
{
}

static inline void
npt_encode_ID3D12StateObjectProperties_SetPipelineStackSize_reply(struct npt_cs_encoder *enc,
                                                                  const struct npt_command_ID3D12StateObjectProperties_SetPipelineStackSize *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12StateObjectProperties,
                                 NPT_METHOD_ID3D12StateObjectProperties_SetPipelineStackSize),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12StateObjectProperties_SetPipelineStackSize(struct npt_dispatch_context *ctx,
                                                              uint32_t cmd_flags,
                                                              uint64_t object_id)
{
    struct npt_command_ID3D12StateObjectProperties_SetPipelineStackSize args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12StateObjectProperties_SetPipelineStackSize_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12STATEOBJECTPROPERTIES);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_SetPipelineStackSize on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12StateObjectProperties_SetPipelineStackSize_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties_SetPipelineStackSize: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12StateObjectProperties_SetPipelineStackSize _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12StateObjectProperties_SetPipelineStackSize, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12StateObjectProperties_SetPipelineStackSize);

    if (ctx->id3d12stateobjectproperties_dispatch_overrides && ctx->id3d12stateobjectproperties_dispatch_overrides->SetPipelineStackSize) {
        ctx->id3d12stateobjectproperties_dispatch_overrides->SetPipelineStackSize(ctx, &args, _original);
    } else {
        _original(args._self, args.PipelineStackSizeInBytes);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12StateObjectProperties_SetPipelineStackSize_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12StateObjectProperties1::GetProgramIdentifier
 */

struct npt_command_ID3D12StateObjectProperties1_GetProgramIdentifier {
    void *_self;
    const WCHAR * pProgramName;
    D3D12_PROGRAM_IDENTIFIER ret;
};

static inline void
npt_decode_ID3D12StateObjectProperties1_GetProgramIdentifier_args_temp(struct npt_cs_decoder *dec,
                                                                       struct npt_command_ID3D12StateObjectProperties1_GetProgramIdentifier *args)
{
    /* Decode input parameters from the wire */
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->pProgramName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->pProgramName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->pProgramName, _wstr_size);
        } else {
            args->pProgramName = NULL;
        }
    }
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_ID3D12StateObjectProperties1_GetProgramIdentifier_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12StateObjectProperties1_GetProgramIdentifier *args)
{
}

static inline void
npt_encode_ID3D12StateObjectProperties1_GetProgramIdentifier_reply(struct npt_cs_encoder *enc,
                                                                   const struct npt_command_ID3D12StateObjectProperties1_GetProgramIdentifier *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12StateObjectProperties1,
                                 NPT_METHOD_ID3D12StateObjectProperties1_GetProgramIdentifier),
        .cmd_return = 0,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_D3D12_PROGRAM_IDENTIFIER(enc, &args->ret);
}

static inline void
npt_dispatch_ID3D12StateObjectProperties1_GetProgramIdentifier(struct npt_dispatch_context *ctx,
                                                               uint32_t cmd_flags,
                                                               uint64_t object_id)
{
    struct npt_command_ID3D12StateObjectProperties1_GetProgramIdentifier args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12StateObjectProperties1_GetProgramIdentifier_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12STATEOBJECTPROPERTIES1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties1_GetProgramIdentifier on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12StateObjectProperties1_GetProgramIdentifier_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12StateObjectProperties1_GetProgramIdentifier: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12StateObjectProperties1_GetProgramIdentifier _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12StateObjectProperties1_GetProgramIdentifier, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12StateObjectProperties1_GetProgramIdentifier);

    if (ctx->id3d12stateobjectproperties1_dispatch_overrides && ctx->id3d12stateobjectproperties1_dispatch_overrides->GetProgramIdentifier) {
        args.ret = ctx->id3d12stateobjectproperties1_dispatch_overrides->GetProgramIdentifier(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret, args.pProgramName);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12StateObjectProperties1_GetProgramIdentifier_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12STATEOBJECTPROPERTIES_H */
