/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d11videodecoder.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D11VIDEODECODER_H
#define NPT_PROTOCOL_HOST_ID3D11VIDEODECODER_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D11VideoDecoder::GetCreationParameters
 */

struct npt_command_ID3D11VideoDecoder_GetCreationParameters {
    void *_self;
    D3D11_VIDEO_DECODER_DESC * pVideoDesc;
    D3D11_VIDEO_DECODER_CONFIG * pConfig;
    HRESULT ret;
};

static inline void
npt_decode_ID3D11VideoDecoder_GetCreationParameters_args_temp(struct npt_cs_decoder *dec,
                                                              struct npt_command_ID3D11VideoDecoder_GetCreationParameters *args)
{
    /* Decode input parameters from the wire */


    /* Allocate temp storage for output-only parameters */
    args->pVideoDesc = npt_cs_decoder_alloc_temp(dec, sizeof(D3D11_VIDEO_DECODER_DESC));
    if (!args->pVideoDesc) return;
    memset(args->pVideoDesc, 0, sizeof(D3D11_VIDEO_DECODER_DESC));
    args->pConfig = npt_cs_decoder_alloc_temp(dec, sizeof(D3D11_VIDEO_DECODER_CONFIG));
    if (!args->pConfig) return;
    memset(args->pConfig, 0, sizeof(D3D11_VIDEO_DECODER_CONFIG));
}

static inline void
npt_replace_ID3D11VideoDecoder_GetCreationParameters_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D11VideoDecoder_GetCreationParameters *args)
{
}

static inline void
npt_encode_ID3D11VideoDecoder_GetCreationParameters_reply(struct npt_cs_encoder *enc,
                                                          const struct npt_command_ID3D11VideoDecoder_GetCreationParameters *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11VideoDecoder,
                                 NPT_METHOD_ID3D11VideoDecoder_GetCreationParameters),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pVideoDesc))
        npt_encode_D3D11_VIDEO_DECODER_DESC(enc, args->pVideoDesc);
    if (npt_encode_simple_pointer(enc, args->pConfig))
        npt_encode_D3D11_VIDEO_DECODER_CONFIG(enc, args->pConfig);
}

static inline void
npt_dispatch_ID3D11VideoDecoder_GetCreationParameters(struct npt_dispatch_context *ctx,
                                                      uint32_t cmd_flags,
                                                      uint64_t object_id)
{
    struct npt_command_ID3D11VideoDecoder_GetCreationParameters args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D11VideoDecoder_GetCreationParameters_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D11VIDEODECODER);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D11VideoDecoder_GetCreationParameters on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D11VideoDecoder_GetCreationParameters_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D11VideoDecoder_GetCreationParameters: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D11VideoDecoder_GetCreationParameters _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D11VideoDecoder_GetCreationParameters, npt_com_vtable(args._self),
        NPT_VTBL_ID3D11VideoDecoder_GetCreationParameters);

    if (ctx->id3d11videodecoder_dispatch_overrides && ctx->id3d11videodecoder_dispatch_overrides->GetCreationParameters) {
        args.ret = ctx->id3d11videodecoder_dispatch_overrides->GetCreationParameters(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pVideoDesc, args.pConfig);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D11VideoDecoder_GetCreationParameters_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D11VideoDecoder::GetDriverHandle
 */

struct npt_command_ID3D11VideoDecoder_GetDriverHandle {
    void *_self;
    HANDLE * pDriverHandle;
    HRESULT ret;
};

static inline void
npt_decode_ID3D11VideoDecoder_GetDriverHandle_args_temp(struct npt_cs_decoder *dec,
                                                        struct npt_command_ID3D11VideoDecoder_GetDriverHandle *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pDriverHandle = npt_cs_decoder_alloc_temp(dec, sizeof(HANDLE));
    if (!args->pDriverHandle) return;
    memset(args->pDriverHandle, 0, sizeof(HANDLE));
}

static inline void
npt_replace_ID3D11VideoDecoder_GetDriverHandle_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D11VideoDecoder_GetDriverHandle *args)
{
}

static inline void
npt_encode_ID3D11VideoDecoder_GetDriverHandle_reply(struct npt_cs_encoder *enc,
                                                    const struct npt_command_ID3D11VideoDecoder_GetDriverHandle *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D11VideoDecoder,
                                 NPT_METHOD_ID3D11VideoDecoder_GetDriverHandle),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_win32_handle(enc, npt_win32_handle_get_id((const void *)(uintptr_t)*args->pDriverHandle));
}

static inline void
npt_dispatch_ID3D11VideoDecoder_GetDriverHandle(struct npt_dispatch_context *ctx,
                                                uint32_t cmd_flags,
                                                uint64_t object_id)
{
    struct npt_command_ID3D11VideoDecoder_GetDriverHandle args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D11VideoDecoder_GetDriverHandle_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D11VIDEODECODER);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D11VideoDecoder_GetDriverHandle on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D11VideoDecoder_GetDriverHandle_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D11VideoDecoder_GetDriverHandle: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D11VideoDecoder_GetDriverHandle _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D11VideoDecoder_GetDriverHandle, npt_com_vtable(args._self),
        NPT_VTBL_ID3D11VideoDecoder_GetDriverHandle);

    if (ctx->id3d11videodecoder_dispatch_overrides && ctx->id3d11videodecoder_dispatch_overrides->GetDriverHandle) {
        args.ret = ctx->id3d11videodecoder_dispatch_overrides->GetDriverHandle(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pDriverHandle);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D11VideoDecoder_GetDriverHandle_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D11VIDEODECODER_H */
