/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12versionedrootsignaturedeserializer.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H
#define NPT_PROTOCOL_HOST_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12VersionedRootSignatureDeserializer::GetRootSignatureDescAtVersion
 */

struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion {
    void *_self;
    D3D_ROOT_SIGNATURE_VERSION convertToVersion;
    const D3D12_VERSIONED_ROOT_SIGNATURE_DESC ** ppDesc;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_args_temp(struct npt_cs_decoder *dec,
                                                                                            struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion *args)
{
    /* Decode input parameters from the wire */
    npt_decode_D3D_ROOT_SIGNATURE_VERSION(dec, &args->convertToVersion);

    /* Allocate temp storage for output-only parameters */

    args->ppDesc = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
    if (!args->ppDesc) return;
    *args->ppDesc = NULL;
}

static inline void
npt_replace_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion *args)
{
}

static inline void
npt_encode_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_reply(struct npt_cs_encoder *enc,
                                                                                        const struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion *args)
{
    /* ID3D12VersionedRootSignatureDeserializer::GetRootSignatureDescAtVersion: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion(struct npt_dispatch_context *ctx,
                                                                                    uint32_t cmd_flags,
                                                                                    uint64_t object_id)
{
    struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion);

    if (ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides && ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides->GetRootSignatureDescAtVersion) {
        args.ret = ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides->GetRootSignatureDescAtVersion(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.convertToVersion, args.ppDesc);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12VersionedRootSignatureDeserializer_GetRootSignatureDescAtVersion_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12VersionedRootSignatureDeserializer::GetUnconvertedRootSignatureDesc
 */

struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc {
    void *_self;
    D3D12_VERSIONED_ROOT_SIGNATURE_DESC ret;
};

static inline void
npt_decode_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_args_temp(struct npt_cs_decoder *dec,
                                                                                              struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc *args)
{
}

static inline void
npt_encode_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_reply(struct npt_cs_encoder *enc,
                                                                                          const struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc *args)
{
    /* ID3D12VersionedRootSignatureDeserializer::GetUnconvertedRootSignatureDesc: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc(struct npt_dispatch_context *ctx,
                                                                                      uint32_t cmd_flags,
                                                                                      uint64_t object_id)
{
    struct npt_command_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc);

    if (ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides && ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides->GetUnconvertedRootSignatureDesc) {
        args.ret = ctx->id3d12versionedrootsignaturedeserializer_dispatch_overrides->GetUnconvertedRootSignatureDesc(ctx, &args, _original);
    } else {
        /* COM x64 aggregate-return ABI: the hidden pointer (&args.ret)
         * rides in the call args; the returned pointer aliases it. */
        (void)_original(args._self, &args.ret);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12VersionedRootSignatureDeserializer_GetUnconvertedRootSignatureDesc_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12VERSIONEDROOTSIGNATUREDESERIALIZER_H */
