/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for idxgiresource.
 */

#ifndef NPT_PROTOCOL_HOST_IDXGIRESOURCE_H
#define NPT_PROTOCOL_HOST_IDXGIRESOURCE_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * IDXGIResource::GetSharedHandle
 */

struct npt_command_IDXGIResource_GetSharedHandle {
    void *_self;
    HANDLE * pSharedHandle;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource_GetSharedHandle_args_temp(struct npt_cs_decoder *dec,
                                                   struct npt_command_IDXGIResource_GetSharedHandle *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pSharedHandle = npt_cs_decoder_alloc_temp(dec, sizeof(HANDLE));
    if (!args->pSharedHandle) return;
    memset(args->pSharedHandle, 0, sizeof(HANDLE));
}

static inline void
npt_replace_IDXGIResource_GetSharedHandle_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource_GetSharedHandle *args)
{
}

static inline void
npt_encode_IDXGIResource_GetSharedHandle_reply(struct npt_cs_encoder *enc,
                                               const struct npt_command_IDXGIResource_GetSharedHandle *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource,
                                 NPT_METHOD_IDXGIResource_GetSharedHandle),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_win32_handle(enc, npt_win32_handle_get_id((const void *)(uintptr_t)*args->pSharedHandle));
}

static inline void
npt_dispatch_IDXGIResource_GetSharedHandle(struct npt_dispatch_context *ctx,
                                           uint32_t cmd_flags,
                                           uint64_t object_id)
{
    struct npt_command_IDXGIResource_GetSharedHandle args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource_GetSharedHandle_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetSharedHandle on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource_GetSharedHandle_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetSharedHandle: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource_GetSharedHandle _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource_GetSharedHandle, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource_GetSharedHandle);

    if (ctx->idxgiresource_dispatch_overrides && ctx->idxgiresource_dispatch_overrides->GetSharedHandle) {
        args.ret = ctx->idxgiresource_dispatch_overrides->GetSharedHandle(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pSharedHandle);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource_GetSharedHandle_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIResource::GetUsage
 */

struct npt_command_IDXGIResource_GetUsage {
    void *_self;
    DXGI_USAGE * pUsage;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource_GetUsage_args_temp(struct npt_cs_decoder *dec,
                                            struct npt_command_IDXGIResource_GetUsage *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pUsage = npt_cs_decoder_alloc_temp(dec, sizeof(DXGI_USAGE));
    if (!args->pUsage) return;
    memset(args->pUsage, 0, sizeof(DXGI_USAGE));
}

static inline void
npt_replace_IDXGIResource_GetUsage_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource_GetUsage *args)
{
}

static inline void
npt_encode_IDXGIResource_GetUsage_reply(struct npt_cs_encoder *enc,
                                        const struct npt_command_IDXGIResource_GetUsage *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource,
                                 NPT_METHOD_IDXGIResource_GetUsage),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pUsage))
        npt_encode_DXGI_USAGE(enc, args->pUsage);
}

static inline void
npt_dispatch_IDXGIResource_GetUsage(struct npt_dispatch_context *ctx,
                                    uint32_t cmd_flags,
                                    uint64_t object_id)
{
    struct npt_command_IDXGIResource_GetUsage args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource_GetUsage_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetUsage on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource_GetUsage_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetUsage: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource_GetUsage _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource_GetUsage, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource_GetUsage);

    if (ctx->idxgiresource_dispatch_overrides && ctx->idxgiresource_dispatch_overrides->GetUsage) {
        args.ret = ctx->idxgiresource_dispatch_overrides->GetUsage(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pUsage);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource_GetUsage_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIResource::SetEvictionPriority
 */

struct npt_command_IDXGIResource_SetEvictionPriority {
    void *_self;
    UINT EvictionPriority;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource_SetEvictionPriority_args_temp(struct npt_cs_decoder *dec,
                                                       struct npt_command_IDXGIResource_SetEvictionPriority *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->EvictionPriority);
    /* Allocate temp storage for output-only parameters */

}

static inline void
npt_replace_IDXGIResource_SetEvictionPriority_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource_SetEvictionPriority *args)
{
}

static inline void
npt_encode_IDXGIResource_SetEvictionPriority_reply(struct npt_cs_encoder *enc,
                                                   const struct npt_command_IDXGIResource_SetEvictionPriority *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource,
                                 NPT_METHOD_IDXGIResource_SetEvictionPriority),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_IDXGIResource_SetEvictionPriority(struct npt_dispatch_context *ctx,
                                               uint32_t cmd_flags,
                                               uint64_t object_id)
{
    struct npt_command_IDXGIResource_SetEvictionPriority args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource_SetEvictionPriority_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_SetEvictionPriority on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource_SetEvictionPriority_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_SetEvictionPriority: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource_SetEvictionPriority _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource_SetEvictionPriority, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource_SetEvictionPriority);

    if (ctx->idxgiresource_dispatch_overrides && ctx->idxgiresource_dispatch_overrides->SetEvictionPriority) {
        args.ret = ctx->idxgiresource_dispatch_overrides->SetEvictionPriority(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.EvictionPriority);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource_SetEvictionPriority_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIResource::GetEvictionPriority
 */

struct npt_command_IDXGIResource_GetEvictionPriority {
    void *_self;
    UINT * pEvictionPriority;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource_GetEvictionPriority_args_temp(struct npt_cs_decoder *dec,
                                                       struct npt_command_IDXGIResource_GetEvictionPriority *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pEvictionPriority = npt_cs_decoder_alloc_temp(dec, sizeof(UINT));
    if (!args->pEvictionPriority) return;
    memset(args->pEvictionPriority, 0, sizeof(UINT));
}

static inline void
npt_replace_IDXGIResource_GetEvictionPriority_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource_GetEvictionPriority *args)
{
}

static inline void
npt_encode_IDXGIResource_GetEvictionPriority_reply(struct npt_cs_encoder *enc,
                                                   const struct npt_command_IDXGIResource_GetEvictionPriority *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource,
                                 NPT_METHOD_IDXGIResource_GetEvictionPriority),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    if (npt_encode_simple_pointer(enc, args->pEvictionPriority))
        npt_encode_UINT(enc, args->pEvictionPriority);
}

static inline void
npt_dispatch_IDXGIResource_GetEvictionPriority(struct npt_dispatch_context *ctx,
                                               uint32_t cmd_flags,
                                               uint64_t object_id)
{
    struct npt_command_IDXGIResource_GetEvictionPriority args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource_GetEvictionPriority_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetEvictionPriority on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource_GetEvictionPriority_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource_GetEvictionPriority: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource_GetEvictionPriority _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource_GetEvictionPriority, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource_GetEvictionPriority);

    if (ctx->idxgiresource_dispatch_overrides && ctx->idxgiresource_dispatch_overrides->GetEvictionPriority) {
        args.ret = ctx->idxgiresource_dispatch_overrides->GetEvictionPriority(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pEvictionPriority);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource_GetEvictionPriority_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIResource1::CreateSubresourceSurface
 */

struct npt_command_IDXGIResource1_CreateSubresourceSurface {
    void *_self;
    UINT index;
    IDXGISurface2 ** ppSurface;
    /* Shadow: the guest-allocated id for ppSurface arrives in the command
     * body (no reply round-trip).  The post-dispatch register pass reads
     * this field and inserts {_guest_id_ppSurface -> *ppSurface} in the
     * context object table. */
    uint64_t _guest_id_ppSurface;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource1_CreateSubresourceSurface_args_temp(struct npt_cs_decoder *dec,
                                                             struct npt_command_IDXGIResource1_CreateSubresourceSurface *args)
{
    /* Decode input parameters from the wire */
    npt_decode_UINT(dec, &args->index);
    {
        uint64_t _gid;
        npt_decode_uint64_t(dec, &_gid);
        args->_guest_id_ppSurface = _gid;
        args->ppSurface = npt_cs_decoder_alloc_temp(dec, sizeof(void *));
        if (!args->ppSurface) return;
        *args->ppSurface = NULL;
    }
    /* Allocate temp storage for output-only parameters */


}

static inline void
npt_replace_IDXGIResource1_CreateSubresourceSurface_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource1_CreateSubresourceSurface *args)
{
}

static inline void
npt_encode_IDXGIResource1_CreateSubresourceSurface_reply(struct npt_cs_encoder *enc,
                                                         const struct npt_command_IDXGIResource1_CreateSubresourceSurface *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource1,
                                 NPT_METHOD_IDXGIResource1_CreateSubresourceSurface),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
/* skip args->ppSurface (guest-allocated id, registered host-side; not in reply) */
}

static inline void
npt_dispatch_IDXGIResource1_CreateSubresourceSurface(struct npt_dispatch_context *ctx,
                                                     uint32_t cmd_flags,
                                                     uint64_t object_id)
{
    struct npt_command_IDXGIResource1_CreateSubresourceSurface args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource1_CreateSubresourceSurface_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource1_CreateSubresourceSurface on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSurface);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource1_CreateSubresourceSurface_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource1_CreateSubresourceSurface: an argument handle is unknown "
                    "to this context");
            npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSurface);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource1_CreateSubresourceSurface _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource1_CreateSubresourceSurface, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource1_CreateSubresourceSurface);

    if (ctx->idxgiresource1_dispatch_overrides && ctx->idxgiresource1_dispatch_overrides->CreateSubresourceSurface) {
        args.ret = ctx->idxgiresource1_dispatch_overrides->CreateSubresourceSurface(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.index, args.ppSurface);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */
    if (args.ppSurface && *args.ppSurface)
        npt_cs_handle_register_guest_id(ctx, args._guest_id_ppSurface, *args.ppSurface, NPT_OBJECT_TYPE_IDXGISURFACE2);
    else if (args.ppSurface)
        npt_cs_handle_register_failed_guest_id(ctx, args._guest_id_ppSurface);

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource1_CreateSubresourceSurface_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * IDXGIResource1::CreateSharedHandle
 */

struct npt_command_IDXGIResource1_CreateSharedHandle {
    void *_self;
    const SECURITY_ATTRIBUTES * pAttributes;
    DWORD dwAccess;
    const WCHAR * lpName;
    HANDLE * pHandle;
    HRESULT ret;
};

static inline void
npt_decode_IDXGIResource1_CreateSharedHandle_args_temp(struct npt_cs_decoder *dec,
                                                       struct npt_command_IDXGIResource1_CreateSharedHandle *args)
{
    /* Decode input parameters from the wire */
    /* pAttributes: non-serializable, skipped */
    npt_decode_DWORD(dec, &args->dwAccess);
    {
        const uint64_t _wstr_size = npt_decode_array_count_unchecked(dec);
        if (_wstr_size) {
            args->lpName = npt_cs_decoder_alloc_temp(dec, _wstr_size);
            if (!args->lpName) return;
            npt_decode_wchar_array(dec, (WCHAR *)args->lpName, _wstr_size);
        } else {
            args->lpName = NULL;
        }
    }

    /* Allocate temp storage for output-only parameters */



    args->pHandle = npt_cs_decoder_alloc_temp(dec, sizeof(HANDLE));
    if (!args->pHandle) return;
    memset(args->pHandle, 0, sizeof(HANDLE));
}

static inline void
npt_replace_IDXGIResource1_CreateSharedHandle_args_handle(struct npt_dispatch_context *ctx, struct npt_command_IDXGIResource1_CreateSharedHandle *args)
{
}

static inline void
npt_encode_IDXGIResource1_CreateSharedHandle_reply(struct npt_cs_encoder *enc,
                                                   const struct npt_command_IDXGIResource1_CreateSharedHandle *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_IDXGIResource1,
                                 NPT_METHOD_IDXGIResource1_CreateSharedHandle),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
    npt_encode_win32_handle(enc, npt_win32_handle_get_id((const void *)(uintptr_t)*args->pHandle));
}

static inline void
npt_dispatch_IDXGIResource1_CreateSharedHandle(struct npt_dispatch_context *ctx,
                                               uint32_t cmd_flags,
                                               uint64_t object_id)
{
    struct npt_command_IDXGIResource1_CreateSharedHandle args;
    memset(&args, 0, sizeof(args));

    npt_decode_IDXGIResource1_CreateSharedHandle_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_IDXGIRESOURCE1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource1_CreateSharedHandle on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_IDXGIResource1_CreateSharedHandle_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping IDXGIResource1_CreateSharedHandle: an argument handle is unknown "
                    "to this context");

            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_IDXGIResource1_CreateSharedHandle _original = NPT_COM_VTBL_FUNC(
        PFN_IDXGIResource1_CreateSharedHandle, npt_com_vtable(args._self),
        NPT_VTBL_IDXGIResource1_CreateSharedHandle);

    if (ctx->idxgiresource1_dispatch_overrides && ctx->idxgiresource1_dispatch_overrides->CreateSharedHandle) {
        args.ret = ctx->idxgiresource1_dispatch_overrides->CreateSharedHandle(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pAttributes, args.dwAccess, args.lpName, args.pHandle);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_IDXGIResource1_CreateSharedHandle_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_IDXGIRESOURCE_H */
