/*
 * Copyright 2026 Turing Software LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * Generated by npt_protocol.py -- do not edit.
 *
 * Command structs and encode/decode for id3d12deviceremovedextendeddata.
 */

#ifndef NPT_PROTOCOL_HOST_ID3D12DEVICEREMOVEDEXTENDEDDATA_H
#define NPT_PROTOCOL_HOST_ID3D12DEVICEREMOVEDEXTENDEDDATA_H

#include "npt_protocol_host_structs.h"
#include "npt_protocol_host_dispatch_types.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wpointer-arith"

/*
 * ID3D12DeviceRemovedExtendedData::GetAutoBreadcrumbsOutput
 */

struct npt_command_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput {
    void *_self;
    D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT * pOutput;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_args_temp(struct npt_cs_decoder *dec,
                                                                              struct npt_command_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pOutput = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT));
    if (!args->pOutput) return;
    memset(args->pOutput, 0, sizeof(D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT));
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput *args)
{
    if (args->pOutput)
        npt_replace_D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT_handle(ctx, (D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT *)args->pOutput);
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_reply(struct npt_cs_encoder *enc,
                                                                          const struct npt_command_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput *args)
{
    /* ID3D12DeviceRemovedExtendedData::GetAutoBreadcrumbsOutput: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput(struct npt_dispatch_context *ctx,
                                                                      uint32_t cmd_flags,
                                                                      uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput);

    if (ctx->id3d12deviceremovedextendeddata_dispatch_overrides && ctx->id3d12deviceremovedextendeddata_dispatch_overrides->GetAutoBreadcrumbsOutput) {
        args.ret = ctx->id3d12deviceremovedextendeddata_dispatch_overrides->GetAutoBreadcrumbsOutput(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pOutput);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData_GetAutoBreadcrumbsOutput_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceRemovedExtendedData::GetPageFaultAllocationOutput
 */

struct npt_command_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput {
    void *_self;
    D3D12_DRED_PAGE_FAULT_OUTPUT * pOutput;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_args_temp(struct npt_cs_decoder *dec,
                                                                                  struct npt_command_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pOutput = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT));
    if (!args->pOutput) return;
    memset(args->pOutput, 0, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT));
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput *args)
{
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_reply(struct npt_cs_encoder *enc,
                                                                              const struct npt_command_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput *args)
{
    /* ID3D12DeviceRemovedExtendedData::GetPageFaultAllocationOutput: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput(struct npt_dispatch_context *ctx,
                                                                          uint32_t cmd_flags,
                                                                          uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput);

    if (ctx->id3d12deviceremovedextendeddata_dispatch_overrides && ctx->id3d12deviceremovedextendeddata_dispatch_overrides->GetPageFaultAllocationOutput) {
        args.ret = ctx->id3d12deviceremovedextendeddata_dispatch_overrides->GetPageFaultAllocationOutput(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pOutput);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData_GetPageFaultAllocationOutput_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceRemovedExtendedData1::GetAutoBreadcrumbsOutput1
 */

struct npt_command_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 {
    void *_self;
    D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT1 * pOutput;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_args_temp(struct npt_cs_decoder *dec,
                                                                                struct npt_command_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pOutput = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT1));
    if (!args->pOutput) return;
    memset(args->pOutput, 0, sizeof(D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT1));
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 *args)
{
    if (args->pOutput)
        npt_replace_D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT1_handle(ctx, (D3D12_DRED_AUTO_BREADCRUMBS_OUTPUT1 *)args->pOutput);
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_reply(struct npt_cs_encoder *enc,
                                                                            const struct npt_command_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 *args)
{
    /* ID3D12DeviceRemovedExtendedData1::GetAutoBreadcrumbsOutput1: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1(struct npt_dispatch_context *ctx,
                                                                        uint32_t cmd_flags,
                                                                        uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1 _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1);

    if (ctx->id3d12deviceremovedextendeddata1_dispatch_overrides && ctx->id3d12deviceremovedextendeddata1_dispatch_overrides->GetAutoBreadcrumbsOutput1) {
        args.ret = ctx->id3d12deviceremovedextendeddata1_dispatch_overrides->GetAutoBreadcrumbsOutput1(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pOutput);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData1_GetAutoBreadcrumbsOutput1_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceRemovedExtendedData1::GetPageFaultAllocationOutput1
 */

struct npt_command_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 {
    void *_self;
    D3D12_DRED_PAGE_FAULT_OUTPUT1 * pOutput;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_args_temp(struct npt_cs_decoder *dec,
                                                                                    struct npt_command_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pOutput = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT1));
    if (!args->pOutput) return;
    memset(args->pOutput, 0, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT1));
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 *args)
{
    if (args->pOutput)
        npt_replace_D3D12_DRED_PAGE_FAULT_OUTPUT1_handle(ctx, (D3D12_DRED_PAGE_FAULT_OUTPUT1 *)args->pOutput);
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_reply(struct npt_cs_encoder *enc,
                                                                                const struct npt_command_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 *args)
{
    /* ID3D12DeviceRemovedExtendedData1::GetPageFaultAllocationOutput1: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1(struct npt_dispatch_context *ctx,
                                                                            uint32_t cmd_flags,
                                                                            uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA1);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1 _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1);

    if (ctx->id3d12deviceremovedextendeddata1_dispatch_overrides && ctx->id3d12deviceremovedextendeddata1_dispatch_overrides->GetPageFaultAllocationOutput1) {
        args.ret = ctx->id3d12deviceremovedextendeddata1_dispatch_overrides->GetPageFaultAllocationOutput1(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pOutput);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData1_GetPageFaultAllocationOutput1_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceRemovedExtendedData2::GetPageFaultAllocationOutput2
 */

struct npt_command_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 {
    void *_self;
    D3D12_DRED_PAGE_FAULT_OUTPUT2 * pOutput;
    HRESULT ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_args_temp(struct npt_cs_decoder *dec,
                                                                                    struct npt_command_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 *args)
{
    /* Decode input parameters from the wire */

    /* Allocate temp storage for output-only parameters */
    args->pOutput = npt_cs_decoder_alloc_temp(dec, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT2));
    if (!args->pOutput) return;
    memset(args->pOutput, 0, sizeof(D3D12_DRED_PAGE_FAULT_OUTPUT2));
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 *args)
{
    if (args->pOutput)
        npt_replace_D3D12_DRED_PAGE_FAULT_OUTPUT2_handle(ctx, (D3D12_DRED_PAGE_FAULT_OUTPUT2 *)args->pOutput);
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_reply(struct npt_cs_encoder *enc,
                                                                                const struct npt_command_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 *args)
{
    /* ID3D12DeviceRemovedExtendedData2::GetPageFaultAllocationOutput2: reply contains a type with
     * runtime-unbounded wire size (e.g. DRED chain pointers, root-
     * signature parameter arrays).  A pre-reserved fixed-size reply
     * slot cannot represent this without truncating the host data, so
     * the guest gets a clean reply-mismatch via the encoder fatal
     * flag rather than a corrupted stream. */
    npt_cs_encoder_set_fatal(enc);
    return;
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2(struct npt_dispatch_context *ctx,
                                                                            uint32_t cmd_flags,
                                                                            uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA2);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2 _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2);

    if (ctx->id3d12deviceremovedextendeddata2_dispatch_overrides && ctx->id3d12deviceremovedextendeddata2_dispatch_overrides->GetPageFaultAllocationOutput2) {
        args.ret = ctx->id3d12deviceremovedextendeddata2_dispatch_overrides->GetPageFaultAllocationOutput2(ctx, &args, _original);
    } else {
        args.ret = _original(args._self, args.pOutput);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData2_GetPageFaultAllocationOutput2_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}

/*
 * ID3D12DeviceRemovedExtendedData2::GetDeviceState
 */

struct npt_command_ID3D12DeviceRemovedExtendedData2_GetDeviceState {
    void *_self;
    D3D12_DRED_DEVICE_STATE ret;
};

static inline void
npt_decode_ID3D12DeviceRemovedExtendedData2_GetDeviceState_args_temp(struct npt_cs_decoder *dec,
                                                                     struct npt_command_ID3D12DeviceRemovedExtendedData2_GetDeviceState *args)
{
    /* Decode input parameters from the wire */
    /* Allocate temp storage for output-only parameters */
}

static inline void
npt_replace_ID3D12DeviceRemovedExtendedData2_GetDeviceState_args_handle(struct npt_dispatch_context *ctx, struct npt_command_ID3D12DeviceRemovedExtendedData2_GetDeviceState *args)
{
}

static inline void
npt_encode_ID3D12DeviceRemovedExtendedData2_GetDeviceState_reply(struct npt_cs_encoder *enc,
                                                                 const struct npt_command_ID3D12DeviceRemovedExtendedData2_GetDeviceState *args)
{
    struct npt_reply_header _reply = {
        .cmd_type = NPT_CMD_TYPE(255, NPT_IFACE_ID_ID3D12DeviceRemovedExtendedData2,
                                 NPT_METHOD_ID3D12DeviceRemovedExtendedData2_GetDeviceState),
        .cmd_return = (uint32_t)args->ret,
    };
    npt_cs_encoder_write(enc, sizeof(_reply), &_reply, sizeof(_reply));
}

static inline void
npt_dispatch_ID3D12DeviceRemovedExtendedData2_GetDeviceState(struct npt_dispatch_context *ctx,
                                                             uint32_t cmd_flags,
                                                             uint64_t object_id)
{
    struct npt_command_ID3D12DeviceRemovedExtendedData2_GetDeviceState args;
    memset(&args, 0, sizeof(args));

    npt_decode_ID3D12DeviceRemovedExtendedData2_GetDeviceState_args_temp(ctx->decoder, &args);

    if (npt_cs_decoder_get_fatal(ctx->decoder))
        return;

    args._self = npt_cs_handle_lookup(ctx, object_id,
                                       NPT_OBJECT_TYPE_ID3D12DEVICEREMOVEDEXTENDEDDATA2);
    if (!args._self) {
        /* The host no longer knows this object -- a guest-side lifetime
         * bug, or a teardown race between a release and a call already
         * on the wire.  A reply-less call is dropped: losing one
         * command on an object that is already gone is a smaller harm
         * than the context teardown a fatal costs.  A call that owes a
         * reply still goes fatal; there is no honest answer to encode,
         * and a silent drop would hang the caller.  Consume the
         * recorded miss either way so it cannot leak into the next
         * command. */
        (void)npt_cs_decoder_take_handle_miss(ctx->decoder);
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData2_GetDeviceState on unregistered object "
                    "0x%016" PRIx64, (uint64_t)object_id);
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    npt_replace_ID3D12DeviceRemovedExtendedData2_GetDeviceState_args_handle(ctx, &args);

    if (npt_cs_decoder_take_handle_miss(ctx->decoder)) {
        /* An argument handle failed to translate; the backend would
         * dereference the NULL left in its place.  Same policy as a
         * missing self: drop when nothing awaits a reply, go fatal
         * when something does. */
        if (!(cmd_flags & NPT_CMD_FLAG_REPLY)) {
            npt_log("dropping ID3D12DeviceRemovedExtendedData2_GetDeviceState: an argument handle is unknown "
                    "to this context");
            npt_cs_decoder_reset_temp_pool(ctx->decoder);
            return;
        }
        npt_cs_decoder_set_fatal(ctx->decoder);
        return;
    }

    PFN_ID3D12DeviceRemovedExtendedData2_GetDeviceState _original = NPT_COM_VTBL_FUNC(
        PFN_ID3D12DeviceRemovedExtendedData2_GetDeviceState, npt_com_vtable(args._self),
        NPT_VTBL_ID3D12DeviceRemovedExtendedData2_GetDeviceState);

    if (ctx->id3d12deviceremovedextendeddata2_dispatch_overrides && ctx->id3d12deviceremovedextendeddata2_dispatch_overrides->GetDeviceState) {
        args.ret = ctx->id3d12deviceremovedextendeddata2_dispatch_overrides->GetDeviceState(ctx, &args, _original);
    } else {
        args.ret = _original(args._self);
    }

    /* Register any output COM handles in the context object table so
     * later commands that reference them can be validated.  The riid
     * expression (if any) lets the generator resolve void** outputs
     * whose type is determined by the caller's riid. */

    if (cmd_flags & NPT_CMD_FLAG_REPLY) {
        if (!npt_cs_decoder_get_fatal(ctx->decoder)) {
            if (npt_cs_encoder_acquire(ctx->encoder)) {
                npt_encode_ID3D12DeviceRemovedExtendedData2_GetDeviceState_reply(ctx->encoder, &args);
                npt_cs_encoder_release(ctx->encoder);
            }
        }
    }

    npt_cs_decoder_reset_temp_pool(ctx->decoder);
}


#pragma GCC diagnostic pop

#endif /* NPT_PROTOCOL_HOST_ID3D12DEVICEREMOVEDEXTENDEDDATA_H */
